# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.add_key_request_any_of import AddKeyRequestAnyOf
from mist_api_v2 import util

from mist_api_v2.models.add_key_request_any_of import AddKeyRequestAnyOf  # noqa: E501

class AddKeyRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, private=None, generate=None, dry=None):  # noqa: E501
        """AddKeyRequest - a model defined in OpenAPI

        :param name: The name of this AddKeyRequest.  # noqa: E501
        :type name: str
        :param private: The private of this AddKeyRequest.  # noqa: E501
        :type private: str
        :param generate: The generate of this AddKeyRequest.  # noqa: E501
        :type generate: bool
        :param dry: The dry of this AddKeyRequest.  # noqa: E501
        :type dry: bool
        """
        self.openapi_types = {
            'name': str,
            'private': str,
            'generate': bool,
            'dry': bool
        }

        self.attribute_map = {
            'name': 'name',
            'private': 'private',
            'generate': 'generate',
            'dry': 'dry'
        }

        self._name = name
        self._private = private
        self._generate = generate
        self._dry = dry

    @classmethod
    def from_dict(cls, dikt) -> 'AddKeyRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddKeyRequest of this AddKeyRequest.  # noqa: E501
        :rtype: AddKeyRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AddKeyRequest.


        :return: The name of this AddKeyRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AddKeyRequest.


        :param name: The name of this AddKeyRequest.
        :type name: str
        """

        self._name = name

    @property
    def private(self):
        """Gets the private of this AddKeyRequest.


        :return: The private of this AddKeyRequest.
        :rtype: str
        """
        return self._private

    @private.setter
    def private(self, private):
        """Sets the private of this AddKeyRequest.


        :param private: The private of this AddKeyRequest.
        :type private: str
        """

        self._private = private

    @property
    def generate(self):
        """Gets the generate of this AddKeyRequest.


        :return: The generate of this AddKeyRequest.
        :rtype: bool
        """
        return self._generate

    @generate.setter
    def generate(self, generate):
        """Sets the generate of this AddKeyRequest.


        :param generate: The generate of this AddKeyRequest.
        :type generate: bool
        """

        self._generate = generate

    @property
    def dry(self):
        """Gets the dry of this AddKeyRequest.


        :return: The dry of this AddKeyRequest.
        :rtype: bool
        """
        return self._dry

    @dry.setter
    def dry(self, dry):
        """Sets the dry of this AddKeyRequest.


        :param dry: The dry of this AddKeyRequest.
        :type dry: bool
        """

        self._dry = dry
