# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class AddKeyRequestAnyOf1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, generate=None, dry=None):  # noqa: E501
        """AddKeyRequestAnyOf1 - a model defined in OpenAPI

        :param name: The name of this AddKeyRequestAnyOf1.  # noqa: E501
        :type name: str
        :param generate: The generate of this AddKeyRequestAnyOf1.  # noqa: E501
        :type generate: bool
        :param dry: The dry of this AddKeyRequestAnyOf1.  # noqa: E501
        :type dry: bool
        """
        self.openapi_types = {
            'name': str,
            'generate': bool,
            'dry': bool
        }

        self.attribute_map = {
            'name': 'name',
            'generate': 'generate',
            'dry': 'dry'
        }

        self._name = name
        self._generate = generate
        self._dry = dry

    @classmethod
    def from_dict(cls, dikt) -> 'AddKeyRequestAnyOf1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddKeyRequest_anyOf_1 of this AddKeyRequestAnyOf1.  # noqa: E501
        :rtype: AddKeyRequestAnyOf1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AddKeyRequestAnyOf1.

        The key's name  # noqa: E501

        :return: The name of this AddKeyRequestAnyOf1.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AddKeyRequestAnyOf1.

        The key's name  # noqa: E501

        :param name: The name of this AddKeyRequestAnyOf1.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def generate(self):
        """Gets the generate of this AddKeyRequestAnyOf1.

        Generate a keypair instead of providing one  # noqa: E501

        :return: The generate of this AddKeyRequestAnyOf1.
        :rtype: bool
        """
        return self._generate

    @generate.setter
    def generate(self, generate):
        """Sets the generate of this AddKeyRequestAnyOf1.

        Generate a keypair instead of providing one  # noqa: E501

        :param generate: The generate of this AddKeyRequestAnyOf1.
        :type generate: bool
        """
        if generate is None:
            raise ValueError("Invalid value for `generate`, must not be `None`")  # noqa: E501

        self._generate = generate

    @property
    def dry(self):
        """Gets the dry of this AddKeyRequestAnyOf1.

        Return generated key without actually adding it  # noqa: E501

        :return: The dry of this AddKeyRequestAnyOf1.
        :rtype: bool
        """
        return self._dry

    @dry.setter
    def dry(self, dry):
        """Sets the dry of this AddKeyRequestAnyOf1.

        Return generated key without actually adding it  # noqa: E501

        :param dry: The dry of this AddKeyRequestAnyOf1.
        :type dry: bool
        """

        self._dry = dry
