# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class AddScheduleRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, schedule=None, location_type=None, entrypoint=None, exec_type=None, description=None):  # noqa: E501
        """AddScheduleRequest - a model defined in OpenAPI

        :param name: The name of this AddScheduleRequest.  # noqa: E501
        :type name: str
        :param schedule: The schedule of this AddScheduleRequest.  # noqa: E501
        :type schedule: str
        :param location_type: The location_type of this AddScheduleRequest.  # noqa: E501
        :type location_type: str
        :param entrypoint: The entrypoint of this AddScheduleRequest.  # noqa: E501
        :type entrypoint: str
        :param exec_type: The exec_type of this AddScheduleRequest.  # noqa: E501
        :type exec_type: str
        :param description: The description of this AddScheduleRequest.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'name': str,
            'schedule': str,
            'location_type': str,
            'entrypoint': str,
            'exec_type': str,
            'description': str
        }

        self.attribute_map = {
            'name': 'name',
            'schedule': 'schedule',
            'location_type': 'location_type',
            'entrypoint': 'entrypoint',
            'exec_type': 'exec_type',
            'description': 'description'
        }

        self._name = name
        self._schedule = schedule
        self._location_type = location_type
        self._entrypoint = entrypoint
        self._exec_type = exec_type
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'AddScheduleRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AddScheduleRequest of this AddScheduleRequest.  # noqa: E501
        :rtype: AddScheduleRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AddScheduleRequest.


        :return: The name of this AddScheduleRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AddScheduleRequest.


        :param name: The name of this AddScheduleRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def schedule(self):
        """Gets the schedule of this AddScheduleRequest.


        :return: The schedule of this AddScheduleRequest.
        :rtype: str
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this AddScheduleRequest.


        :param schedule: The schedule of this AddScheduleRequest.
        :type schedule: str
        """
        if schedule is None:
            raise ValueError("Invalid value for `schedule`, must not be `None`")  # noqa: E501

        self._schedule = schedule

    @property
    def location_type(self):
        """Gets the location_type of this AddScheduleRequest.


        :return: The location_type of this AddScheduleRequest.
        :rtype: str
        """
        return self._location_type

    @location_type.setter
    def location_type(self, location_type):
        """Sets the location_type of this AddScheduleRequest.


        :param location_type: The location_type of this AddScheduleRequest.
        :type location_type: str
        """
        allowed_values = ["inline", "github", "url"]  # noqa: E501
        if location_type not in allowed_values:
            raise ValueError(
                "Invalid value for `location_type` ({0}), must be one of {1}"
                .format(location_type, allowed_values)
            )

        self._location_type = location_type

    @property
    def entrypoint(self):
        """Gets the entrypoint of this AddScheduleRequest.


        :return: The entrypoint of this AddScheduleRequest.
        :rtype: str
        """
        return self._entrypoint

    @entrypoint.setter
    def entrypoint(self, entrypoint):
        """Sets the entrypoint of this AddScheduleRequest.


        :param entrypoint: The entrypoint of this AddScheduleRequest.
        :type entrypoint: str
        """

        self._entrypoint = entrypoint

    @property
    def exec_type(self):
        """Gets the exec_type of this AddScheduleRequest.


        :return: The exec_type of this AddScheduleRequest.
        :rtype: str
        """
        return self._exec_type

    @exec_type.setter
    def exec_type(self, exec_type):
        """Sets the exec_type of this AddScheduleRequest.


        :param exec_type: The exec_type of this AddScheduleRequest.
        :type exec_type: str
        """
        allowed_values = ["executable", "ansible"]  # noqa: E501
        if exec_type not in allowed_values:
            raise ValueError(
                "Invalid value for `exec_type` ({0}), must be one of {1}"
                .format(exec_type, allowed_values)
            )

        self._exec_type = exec_type

    @property
    def description(self):
        """Gets the description of this AddScheduleRequest.


        :return: The description of this AddScheduleRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AddScheduleRequest.


        :param description: The description of this AddScheduleRequest.
        :type description: str
        """

        self._description = description
