# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class AmazonRegions(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AP_NORTHEAST_1 = "ap-northeast-1"
    AP_NORTHEAST_2 = "ap-northeast-2"
    AP_NORTHEAST_3 = "ap-northeast-3"
    AP_SOUTHEAST_1 = "ap-southeast-1"
    AP_SOUTHEAST_2 = "ap-southeast-2"
    EU_CENTRAL_1 = "eu-central-1"
    EU_WEST_1 = "eu-west-1"
    EU_WEST_2 = "eu-west-2"
    EU_WEST_3 = "eu-west-3"
    EU_NORTH_1 = "eu-north-1"
    CA_CENTRAL_1 = "ca-central-1"
    SA_EAST_1 = "sa-east-1"
    US_EAST_1 = "us-east-1"
    US_WEST_1 = "us-west-1"
    US_WEST_2 = "us-west-2"
    US_EAST_2 = "us-east-2"
    AP_SOUTH_1 = "ap-south-1"
    AP_EAST_1 = "ap-east-1"
    CN_NORTH_1 = "cn-north-1"
    CN_NORTHWEST_1 = "cn-northwest-1"
    US_GOV_WEST_1 = "us-gov-west-1"
    US_GOV_EAST_1 = "us-gov-east-1"
    def __init__(self):  # noqa: E501
        """AmazonRegions - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AmazonRegions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmazonRegions of this AmazonRegions.  # noqa: E501
        :rtype: AmazonRegions
        """
        return util.deserialize_model(dikt, cls)
