# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class AmazonCredentials(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, provider=None, apikey=None, apisecret=None):  # noqa: E501
        """AmazonCredentials - a model defined in OpenAPI

        :param provider: The provider of this AmazonCredentials.  # noqa: E501
        :type provider: str
        :param apikey: The apikey of this AmazonCredentials.  # noqa: E501
        :type apikey: str
        :param apisecret: The apisecret of this AmazonCredentials.  # noqa: E501
        :type apisecret: str
        """
        self.openapi_types = {
            'provider': str,
            'apikey': str,
            'apisecret': str
        }

        self.attribute_map = {
            'provider': 'provider',
            'apikey': 'apikey',
            'apisecret': 'apisecret'
        }

        self._provider = provider
        self._apikey = apikey
        self._apisecret = apisecret

    @classmethod
    def from_dict(cls, dikt) -> 'AmazonCredentials':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AmazonCredentials of this AmazonCredentials.  # noqa: E501
        :rtype: AmazonCredentials
        """
        return util.deserialize_model(dikt, cls)

    @property
    def provider(self):
        """Gets the provider of this AmazonCredentials.


        :return: The provider of this AmazonCredentials.
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this AmazonCredentials.


        :param provider: The provider of this AmazonCredentials.
        :type provider: str
        """

        self._provider = provider

    @property
    def apikey(self):
        """Gets the apikey of this AmazonCredentials.

        Your AWS API key  # noqa: E501

        :return: The apikey of this AmazonCredentials.
        :rtype: str
        """
        return self._apikey

    @apikey.setter
    def apikey(self, apikey):
        """Sets the apikey of this AmazonCredentials.

        Your AWS API key  # noqa: E501

        :param apikey: The apikey of this AmazonCredentials.
        :type apikey: str
        """
        if apikey is None:
            raise ValueError("Invalid value for `apikey`, must not be `None`")  # noqa: E501

        self._apikey = apikey

    @property
    def apisecret(self):
        """Gets the apisecret of this AmazonCredentials.

        Your AWS API secret  # noqa: E501

        :return: The apisecret of this AmazonCredentials.
        :rtype: str
        """
        return self._apisecret

    @apisecret.setter
    def apisecret(self, apisecret):
        """Sets the apisecret of this AmazonCredentials.

        Your AWS API secret  # noqa: E501

        :param apisecret: The apisecret of this AmazonCredentials.
        :type apisecret: str
        """
        if apisecret is None:
            raise ValueError("Invalid value for `apisecret`, must not be `None`")  # noqa: E501

        self._apisecret = apisecret
