# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class CreateMachineResponseOneOf1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, plan=None):  # noqa: E501
        """CreateMachineResponseOneOf1 - a model defined in OpenAPI

        :param plan: The plan of this CreateMachineResponseOneOf1.  # noqa: E501
        :type plan: object
        """
        self.openapi_types = {
            'plan': object
        }

        self.attribute_map = {
            'plan': 'plan'
        }

        self._plan = plan

    @classmethod
    def from_dict(cls, dikt) -> 'CreateMachineResponseOneOf1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateMachineResponse_oneOf_1 of this CreateMachineResponseOneOf1.  # noqa: E501
        :rtype: CreateMachineResponseOneOf1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plan(self):
        """Gets the plan of this CreateMachineResponseOneOf1.


        :return: The plan of this CreateMachineResponseOneOf1.
        :rtype: object
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this CreateMachineResponseOneOf1.


        :param plan: The plan of this CreateMachineResponseOneOf1.
        :type plan: object
        """

        self._plan = plan
