# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.cluster_providers import ClusterProviders
from mist_api_v2.models.create_cluster_request_all_of import CreateClusterRequestAllOf
from mist_api_v2 import util

from mist_api_v2.models.cluster_providers import ClusterProviders  # noqa: E501
from mist_api_v2.models.create_cluster_request_all_of import CreateClusterRequestAllOf  # noqa: E501

class CreateClusterRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, cloud=None, provider=None):  # noqa: E501
        """CreateClusterRequest - a model defined in OpenAPI

        :param title: The title of this CreateClusterRequest.  # noqa: E501
        :type title: str
        :param cloud: The cloud of this CreateClusterRequest.  # noqa: E501
        :type cloud: str
        :param provider: The provider of this CreateClusterRequest.  # noqa: E501
        :type provider: ClusterProviders
        """
        self.openapi_types = {
            'title': str,
            'cloud': str,
            'provider': ClusterProviders
        }

        self.attribute_map = {
            'title': 'title',
            'cloud': 'cloud',
            'provider': 'provider'
        }

        self._title = title
        self._cloud = cloud
        self._provider = provider

    @classmethod
    def from_dict(cls, dikt) -> 'CreateClusterRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateClusterRequest of this CreateClusterRequest.  # noqa: E501
        :rtype: CreateClusterRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self):
        """Gets the title of this CreateClusterRequest.

        The name of the cluster to create  # noqa: E501

        :return: The title of this CreateClusterRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CreateClusterRequest.

        The name of the cluster to create  # noqa: E501

        :param title: The title of this CreateClusterRequest.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def cloud(self):
        """Gets the cloud of this CreateClusterRequest.

        The cloud the cluster belongs to  # noqa: E501

        :return: The cloud of this CreateClusterRequest.
        :rtype: str
        """
        return self._cloud

    @cloud.setter
    def cloud(self, cloud):
        """Sets the cloud of this CreateClusterRequest.

        The cloud the cluster belongs to  # noqa: E501

        :param cloud: The cloud of this CreateClusterRequest.
        :type cloud: str
        """
        if cloud is None:
            raise ValueError("Invalid value for `cloud`, must not be `None`")  # noqa: E501

        self._cloud = cloud

    @property
    def provider(self):
        """Gets the provider of this CreateClusterRequest.


        :return: The provider of this CreateClusterRequest.
        :rtype: ClusterProviders
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this CreateClusterRequest.


        :param provider: The provider of this CreateClusterRequest.
        :type provider: ClusterProviders
        """

        self._provider = provider
