# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class CreateClusterResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, job_id=None):  # noqa: E501
        """CreateClusterResponse - a model defined in OpenAPI

        :param job_id: The job_id of this CreateClusterResponse.  # noqa: E501
        :type job_id: str
        """
        self.openapi_types = {
            'job_id': str
        }

        self.attribute_map = {
            'job_id': 'jobId'
        }

        self._job_id = job_id

    @classmethod
    def from_dict(cls, dikt) -> 'CreateClusterResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateClusterResponse of this CreateClusterResponse.  # noqa: E501
        :rtype: CreateClusterResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self):
        """Gets the job_id of this CreateClusterResponse.


        :return: The job_id of this CreateClusterResponse.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this CreateClusterResponse.


        :param job_id: The job_id of this CreateClusterResponse.
        :type job_id: str
        """

        self._job_id = job_id
