# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class DestroyClusterResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, job_id=None, cloud=None, cluster=None):  # noqa: E501
        """DestroyClusterResponse - a model defined in OpenAPI

        :param job_id: The job_id of this DestroyClusterResponse.  # noqa: E501
        :type job_id: str
        :param cloud: The cloud of this DestroyClusterResponse.  # noqa: E501
        :type cloud: str
        :param cluster: The cluster of this DestroyClusterResponse.  # noqa: E501
        :type cluster: str
        """
        self.openapi_types = {
            'job_id': str,
            'cloud': str,
            'cluster': str
        }

        self.attribute_map = {
            'job_id': 'jobId',
            'cloud': 'cloud',
            'cluster': 'cluster'
        }

        self._job_id = job_id
        self._cloud = cloud
        self._cluster = cluster

    @classmethod
    def from_dict(cls, dikt) -> 'DestroyClusterResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DestroyClusterResponse of this DestroyClusterResponse.  # noqa: E501
        :rtype: DestroyClusterResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self):
        """Gets the job_id of this DestroyClusterResponse.


        :return: The job_id of this DestroyClusterResponse.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this DestroyClusterResponse.


        :param job_id: The job_id of this DestroyClusterResponse.
        :type job_id: str
        """

        self._job_id = job_id

    @property
    def cloud(self):
        """Gets the cloud of this DestroyClusterResponse.


        :return: The cloud of this DestroyClusterResponse.
        :rtype: str
        """
        return self._cloud

    @cloud.setter
    def cloud(self, cloud):
        """Sets the cloud of this DestroyClusterResponse.


        :param cloud: The cloud of this DestroyClusterResponse.
        :type cloud: str
        """

        self._cloud = cloud

    @property
    def cluster(self):
        """Gets the cluster of this DestroyClusterResponse.


        :return: The cluster of this DestroyClusterResponse.
        :rtype: str
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this DestroyClusterResponse.


        :param cluster: The cluster of this DestroyClusterResponse.
        :type cluster: str
        """

        self._cluster = cluster
