# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.edit_machine_request_expiration import EditMachineRequestExpiration
from mist_api_v2 import util

from mist_api_v2.models.edit_machine_request_expiration import EditMachineRequestExpiration  # noqa: E501

class EditMachineRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, expiration=None):  # noqa: E501
        """EditMachineRequest - a model defined in OpenAPI

        :param expiration: The expiration of this EditMachineRequest.  # noqa: E501
        :type expiration: EditMachineRequestExpiration
        """
        self.openapi_types = {
            'expiration': EditMachineRequestExpiration
        }

        self.attribute_map = {
            'expiration': 'expiration'
        }

        self._expiration = expiration

    @classmethod
    def from_dict(cls, dikt) -> 'EditMachineRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EditMachineRequest of this EditMachineRequest.  # noqa: E501
        :rtype: EditMachineRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expiration(self):
        """Gets the expiration of this EditMachineRequest.


        :return: The expiration of this EditMachineRequest.
        :rtype: EditMachineRequestExpiration
        """
        return self._expiration

    @expiration.setter
    def expiration(self, expiration):
        """Sets the expiration of this EditMachineRequest.


        :param expiration: The expiration of this EditMachineRequest.
        :type expiration: EditMachineRequestExpiration
        """

        self._expiration = expiration
