# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.equinix_metal_create_machine_request_net_ip_addresses import EquinixMetalCreateMachineRequestNetIpAddresses
from mist_api_v2 import util

from mist_api_v2.models.equinix_metal_create_machine_request_net_ip_addresses import EquinixMetalCreateMachineRequestNetIpAddresses  # noqa: E501

class EquinixMetalCreateMachineRequestNet(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ip_addresses=None):  # noqa: E501
        """EquinixMetalCreateMachineRequestNet - a model defined in OpenAPI

        :param ip_addresses: The ip_addresses of this EquinixMetalCreateMachineRequestNet.  # noqa: E501
        :type ip_addresses: List[EquinixMetalCreateMachineRequestNetIpAddresses]
        """
        self.openapi_types = {
            'ip_addresses': List[EquinixMetalCreateMachineRequestNetIpAddresses]
        }

        self.attribute_map = {
            'ip_addresses': 'ip_addresses'
        }

        self._ip_addresses = ip_addresses

    @classmethod
    def from_dict(cls, dikt) -> 'EquinixMetalCreateMachineRequestNet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EquinixMetalCreateMachineRequest_net of this EquinixMetalCreateMachineRequestNet.  # noqa: E501
        :rtype: EquinixMetalCreateMachineRequestNet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ip_addresses(self):
        """Gets the ip_addresses of this EquinixMetalCreateMachineRequestNet.

        Specify addresses to be created with your machine.By default Equinix configures public IPv4, public IPv6, and private IPv4  # noqa: E501

        :return: The ip_addresses of this EquinixMetalCreateMachineRequestNet.
        :rtype: List[EquinixMetalCreateMachineRequestNetIpAddresses]
        """
        return self._ip_addresses

    @ip_addresses.setter
    def ip_addresses(self, ip_addresses):
        """Sets the ip_addresses of this EquinixMetalCreateMachineRequestNet.

        Specify addresses to be created with your machine.By default Equinix configures public IPv4, public IPv6, and private IPv4  # noqa: E501

        :param ip_addresses: The ip_addresses of this EquinixMetalCreateMachineRequestNet.
        :type ip_addresses: List[EquinixMetalCreateMachineRequestNetIpAddresses]
        """

        self._ip_addresses = ip_addresses
