# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.equinix_metal_create_machine_request_net import EquinixMetalCreateMachineRequestNet
from mist_api_v2.models.one_ofobjectobject import OneOfobjectobject
from mist_api_v2 import util

from mist_api_v2.models.equinix_metal_create_machine_request_net import EquinixMetalCreateMachineRequestNet  # noqa: E501
from mist_api_v2.models.one_ofobjectobject import OneOfobjectobject  # noqa: E501

class EquinixMetalCreateMachineRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, volumes=None, net=None):  # noqa: E501
        """EquinixMetalCreateMachineRequest - a model defined in OpenAPI

        :param volumes: The volumes of this EquinixMetalCreateMachineRequest.  # noqa: E501
        :type volumes: List[OneOfobjectobject]
        :param net: The net of this EquinixMetalCreateMachineRequest.  # noqa: E501
        :type net: EquinixMetalCreateMachineRequestNet
        """
        self.openapi_types = {
            'volumes': List[OneOfobjectobject],
            'net': EquinixMetalCreateMachineRequestNet
        }

        self.attribute_map = {
            'volumes': 'volumes',
            'net': 'net'
        }

        self._volumes = volumes
        self._net = net

    @classmethod
    def from_dict(cls, dikt) -> 'EquinixMetalCreateMachineRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EquinixMetalCreateMachineRequest of this EquinixMetalCreateMachineRequest.  # noqa: E501
        :rtype: EquinixMetalCreateMachineRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def volumes(self):
        """Gets the volumes of this EquinixMetalCreateMachineRequest.


        :return: The volumes of this EquinixMetalCreateMachineRequest.
        :rtype: List[OneOfobjectobject]
        """
        return self._volumes

    @volumes.setter
    def volumes(self, volumes):
        """Sets the volumes of this EquinixMetalCreateMachineRequest.


        :param volumes: The volumes of this EquinixMetalCreateMachineRequest.
        :type volumes: List[OneOfobjectobject]
        """

        self._volumes = volumes

    @property
    def net(self):
        """Gets the net of this EquinixMetalCreateMachineRequest.


        :return: The net of this EquinixMetalCreateMachineRequest.
        :rtype: EquinixMetalCreateMachineRequestNet
        """
        return self._net

    @net.setter
    def net(self, net):
        """Sets the net of this EquinixMetalCreateMachineRequest.


        :param net: The net of this EquinixMetalCreateMachineRequest.
        :type net: EquinixMetalCreateMachineRequestNet
        """

        self._net = net
