# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class GoogleKey(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, key=None, user=None):  # noqa: E501
        """GoogleKey - a model defined in OpenAPI

        :param key: The key of this GoogleKey.  # noqa: E501
        :type key: str
        :param user: The user of this GoogleKey.  # noqa: E501
        :type user: str
        """
        self.openapi_types = {
            'key': str,
            'user': str
        }

        self.attribute_map = {
            'key': 'key',
            'user': 'user'
        }

        self._key = key
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'GoogleKey':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GoogleKey of this GoogleKey.  # noqa: E501
        :rtype: GoogleKey
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self):
        """Gets the key of this GoogleKey.

        Name or ID of the SSH key to deploy  # noqa: E501

        :return: The key of this GoogleKey.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this GoogleKey.

        Name or ID of the SSH key to deploy  # noqa: E501

        :param key: The key of this GoogleKey.
        :type key: str
        """

        self._key = key

    @property
    def user(self):
        """Gets the user of this GoogleKey.

        SSH user, defaults to 'user'  # noqa: E501

        :return: The user of this GoogleKey.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this GoogleKey.

        SSH user, defaults to 'user'  # noqa: E501

        :param user: The user of this GoogleKey.
        :type user: str
        """

        self._user = user
