# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class IntervalScheduleEntry(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, every=None, period=None):  # noqa: E501
        """IntervalScheduleEntry - a model defined in OpenAPI

        :param every: The every of this IntervalScheduleEntry.  # noqa: E501
        :type every: int
        :param period: The period of this IntervalScheduleEntry.  # noqa: E501
        :type period: str
        """
        self.openapi_types = {
            'every': int,
            'period': str
        }

        self.attribute_map = {
            'every': 'every',
            'period': 'period'
        }

        self._every = every
        self._period = period

    @classmethod
    def from_dict(cls, dikt) -> 'IntervalScheduleEntry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IntervalSchedule_entry of this IntervalScheduleEntry.  # noqa: E501
        :rtype: IntervalScheduleEntry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def every(self):
        """Gets the every of this IntervalScheduleEntry.


        :return: The every of this IntervalScheduleEntry.
        :rtype: int
        """
        return self._every

    @every.setter
    def every(self, every):
        """Sets the every of this IntervalScheduleEntry.


        :param every: The every of this IntervalScheduleEntry.
        :type every: int
        """
        if every is None:
            raise ValueError("Invalid value for `every`, must not be `None`")  # noqa: E501

        self._every = every

    @property
    def period(self):
        """Gets the period of this IntervalScheduleEntry.


        :return: The period of this IntervalScheduleEntry.
        :rtype: str
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this IntervalScheduleEntry.


        :param period: The period of this IntervalScheduleEntry.
        :type period: str
        """
        allowed_values = ["minutes", "hours", "days"]  # noqa: E501
        if period not in allowed_values:
            raise ValueError(
                "Invalid value for `period` ({0}), must be one of {1}"
                .format(period, allowed_values)
            )

        self._period = period
