# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class MachineState(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    RUNNING = "running"
    STARTING = "starting"
    STOPPING = "stopping"
    STOPPED = "stopped"
    PENDING = "pending"
    SUSPENDED = "suspended"
    TERMINATED = "terminated"
    ERROR = "error"
    REBOOTING = "rebooting"
    PAUSED = "paused"
    RECONFIGURING = "reconfiguring"
    UNKNOWN = "unknown"
    UPDATING = "updating"
    MIGRATING = "migrating"
    NORMAL = "normal"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    def __init__(self):  # noqa: E501
        """MachineState - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'MachineState':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineState of this MachineState.  # noqa: E501
        :rtype: MachineState
        """
        return util.deserialize_model(dikt, cls)
