# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class OneOffSchedule(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datetime=None, schedule_type=None):  # noqa: E501
        """OneOffSchedule - a model defined in OpenAPI

        :param datetime: The datetime of this OneOffSchedule.  # noqa: E501
        :type datetime: datetime
        :param schedule_type: The schedule_type of this OneOffSchedule.  # noqa: E501
        :type schedule_type: str
        """
        self.openapi_types = {
            'datetime': datetime,
            'schedule_type': str
        }

        self.attribute_map = {
            'datetime': 'datetime',
            'schedule_type': 'schedule_type'
        }

        self._datetime = datetime
        self._schedule_type = schedule_type

    @classmethod
    def from_dict(cls, dikt) -> 'OneOffSchedule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OneOffSchedule of this OneOffSchedule.  # noqa: E501
        :rtype: OneOffSchedule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datetime(self):
        """Gets the datetime of this OneOffSchedule.

        When one_off schedule should run, e.g 2021-09-22T18:19:28Z  # noqa: E501

        :return: The datetime of this OneOffSchedule.
        :rtype: datetime
        """
        return self._datetime

    @datetime.setter
    def datetime(self, datetime):
        """Sets the datetime of this OneOffSchedule.

        When one_off schedule should run, e.g 2021-09-22T18:19:28Z  # noqa: E501

        :param datetime: The datetime of this OneOffSchedule.
        :type datetime: datetime
        """
        if datetime is None:
            raise ValueError("Invalid value for `datetime`, must not be `None`")  # noqa: E501

        self._datetime = datetime

    @property
    def schedule_type(self):
        """Gets the schedule_type of this OneOffSchedule.


        :return: The schedule_type of this OneOffSchedule.
        :rtype: str
        """
        return self._schedule_type

    @schedule_type.setter
    def schedule_type(self, schedule_type):
        """Sets the schedule_type of this OneOffSchedule.


        :param schedule_type: The schedule_type of this OneOffSchedule.
        :type schedule_type: str
        """
        allowed_values = ["one_off"]  # noqa: E501
        if schedule_type not in allowed_values:
            raise ValueError(
                "Invalid value for `schedule_type` ({0}), must be one of {1}"
                .format(schedule_type, allowed_values)
            )

        self._schedule_type = schedule_type
