# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.openstack_cloud_features import OpenstackCloudFeatures
from mist_api_v2.models.openstack_credentials import OpenstackCredentials
from mist_api_v2 import util

from mist_api_v2.models.openstack_cloud_features import OpenstackCloudFeatures  # noqa: E501
from mist_api_v2.models.openstack_credentials import OpenstackCredentials  # noqa: E501

class OpenstackCloudRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, provider=None, credentials=None, features=None):  # noqa: E501
        """OpenstackCloudRequest - a model defined in OpenAPI

        :param provider: The provider of this OpenstackCloudRequest.  # noqa: E501
        :type provider: str
        :param credentials: The credentials of this OpenstackCloudRequest.  # noqa: E501
        :type credentials: OpenstackCredentials
        :param features: The features of this OpenstackCloudRequest.  # noqa: E501
        :type features: OpenstackCloudFeatures
        """
        self.openapi_types = {
            'provider': str,
            'credentials': OpenstackCredentials,
            'features': OpenstackCloudFeatures
        }

        self.attribute_map = {
            'provider': 'provider',
            'credentials': 'credentials',
            'features': 'features'
        }

        self._provider = provider
        self._credentials = credentials
        self._features = features

    @classmethod
    def from_dict(cls, dikt) -> 'OpenstackCloudRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OpenstackCloudRequest of this OpenstackCloudRequest.  # noqa: E501
        :rtype: OpenstackCloudRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def provider(self):
        """Gets the provider of this OpenstackCloudRequest.


        :return: The provider of this OpenstackCloudRequest.
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this OpenstackCloudRequest.


        :param provider: The provider of this OpenstackCloudRequest.
        :type provider: str
        """
        allowed_values = ["openstack"]  # noqa: E501
        if provider not in allowed_values:
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def credentials(self):
        """Gets the credentials of this OpenstackCloudRequest.


        :return: The credentials of this OpenstackCloudRequest.
        :rtype: OpenstackCredentials
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """Sets the credentials of this OpenstackCloudRequest.


        :param credentials: The credentials of this OpenstackCloudRequest.
        :type credentials: OpenstackCredentials
        """
        if credentials is None:
            raise ValueError("Invalid value for `credentials`, must not be `None`")  # noqa: E501

        self._credentials = credentials

    @property
    def features(self):
        """Gets the features of this OpenstackCloudRequest.


        :return: The features of this OpenstackCloudRequest.
        :rtype: OpenstackCloudFeatures
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this OpenstackCloudRequest.


        :param features: The features of this OpenstackCloudRequest.
        :type features: OpenstackCloudFeatures
        """

        self._features = features
