# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.other_cloud_features import OtherCloudFeatures
from mist_api_v2.models.other_credentials import OtherCredentials
from mist_api_v2 import util

from mist_api_v2.models.other_cloud_features import OtherCloudFeatures  # noqa: E501
from mist_api_v2.models.other_credentials import OtherCredentials  # noqa: E501

class OtherCloudRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, provider=None, credentials=None, features=None):  # noqa: E501
        """OtherCloudRequest - a model defined in OpenAPI

        :param provider: The provider of this OtherCloudRequest.  # noqa: E501
        :type provider: str
        :param credentials: The credentials of this OtherCloudRequest.  # noqa: E501
        :type credentials: OtherCredentials
        :param features: The features of this OtherCloudRequest.  # noqa: E501
        :type features: OtherCloudFeatures
        """
        self.openapi_types = {
            'provider': str,
            'credentials': OtherCredentials,
            'features': OtherCloudFeatures
        }

        self.attribute_map = {
            'provider': 'provider',
            'credentials': 'credentials',
            'features': 'features'
        }

        self._provider = provider
        self._credentials = credentials
        self._features = features

    @classmethod
    def from_dict(cls, dikt) -> 'OtherCloudRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OtherCloudRequest of this OtherCloudRequest.  # noqa: E501
        :rtype: OtherCloudRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def provider(self):
        """Gets the provider of this OtherCloudRequest.


        :return: The provider of this OtherCloudRequest.
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this OtherCloudRequest.


        :param provider: The provider of this OtherCloudRequest.
        :type provider: str
        """
        allowed_values = ["other"]  # noqa: E501
        if provider not in allowed_values:
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def credentials(self):
        """Gets the credentials of this OtherCloudRequest.


        :return: The credentials of this OtherCloudRequest.
        :rtype: OtherCredentials
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """Sets the credentials of this OtherCloudRequest.


        :param credentials: The credentials of this OtherCloudRequest.
        :type credentials: OtherCredentials
        """
        if credentials is None:
            raise ValueError("Invalid value for `credentials`, must not be `None`")  # noqa: E501

        self._credentials = credentials

    @property
    def features(self):
        """Gets the features of this OtherCloudRequest.


        :return: The features of this OtherCloudRequest.
        :rtype: OtherCloudFeatures
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this OtherCloudRequest.


        :param features: The features of this OtherCloudRequest.
        :type features: OtherCloudFeatures
        """

        self._features = features
