# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class RebootAction(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, action_type=None):  # noqa: E501
        """RebootAction - a model defined in OpenAPI

        :param action_type: The action_type of this RebootAction.  # noqa: E501
        :type action_type: str
        """
        self.openapi_types = {
            'action_type': str
        }

        self.attribute_map = {
            'action_type': 'action_type'
        }

        self._action_type = action_type

    @classmethod
    def from_dict(cls, dikt) -> 'RebootAction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RebootAction of this RebootAction.  # noqa: E501
        :rtype: RebootAction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def action_type(self):
        """Gets the action_type of this RebootAction.


        :return: The action_type of this RebootAction.
        :rtype: str
        """
        return self._action_type

    @action_type.setter
    def action_type(self, action_type):
        """Sets the action_type of this RebootAction.


        :param action_type: The action_type of this RebootAction.
        :type action_type: str
        """
        allowed_values = ["reboot"]  # noqa: E501
        if action_type not in allowed_values:
            raise ValueError(
                "Invalid value for `action_type` ({0}), must be one of {1}"
                .format(action_type, allowed_values)
            )

        self._action_type = action_type
