# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class ResourceCount(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None):  # noqa: E501
        """ResourceCount - a model defined in OpenAPI

        :param total: The total of this ResourceCount.  # noqa: E501
        :type total: int
        """
        self.openapi_types = {
            'total': int
        }

        self.attribute_map = {
            'total': 'total'
        }

        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'ResourceCount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResourceCount of this ResourceCount.  # noqa: E501
        :rtype: ResourceCount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self):
        """Gets the total of this ResourceCount.


        :return: The total of this ResourceCount.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this ResourceCount.


        :param total: The total of this ResourceCount.
        :type total: int
        """

        self._total = total
