# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2 import util


class SupportedSubnetProviders(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AMAZON = "amazon"
    AZURE = "azure"
    GOOGLE = "google"
    ALIBABA = "alibaba"
    OPENSTACK = "openstack"
    VEXXHOST = "vexxhost"
    def __init__(self):  # noqa: E501
        """SupportedSubnetProviders - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SupportedSubnetProviders':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SupportedSubnetProviders of this SupportedSubnetProviders.  # noqa: E501
        :rtype: SupportedSubnetProviders
        """
        return util.deserialize_model(dikt, cls)
