# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.tag_resources_request_operations import TagResourcesRequestOperations
from mist_api_v2 import util

from mist_api_v2.models.tag_resources_request_operations import TagResourcesRequestOperations  # noqa: E501

class TagResourcesRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, operations=None):  # noqa: E501
        """TagResourcesRequest - a model defined in OpenAPI

        :param operations: The operations of this TagResourcesRequest.  # noqa: E501
        :type operations: List[TagResourcesRequestOperations]
        """
        self.openapi_types = {
            'operations': List[TagResourcesRequestOperations]
        }

        self.attribute_map = {
            'operations': 'operations'
        }

        self._operations = operations

    @classmethod
    def from_dict(cls, dikt) -> 'TagResourcesRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TagResourcesRequest of this TagResourcesRequest.  # noqa: E501
        :rtype: TagResourcesRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def operations(self):
        """Gets the operations of this TagResourcesRequest.


        :return: The operations of this TagResourcesRequest.
        :rtype: List[TagResourcesRequestOperations]
        """
        return self._operations

    @operations.setter
    def operations(self, operations):
        """Sets the operations of this TagResourcesRequest.


        :param operations: The operations of this TagResourcesRequest.
        :type operations: List[TagResourcesRequestOperations]
        """

        self._operations = operations
