# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.resource_ids import ResourceIds
from mist_api_v2.models.tag_name import TagName
from mist_api_v2 import util

from mist_api_v2.models.resource_ids import ResourceIds  # noqa: E501
from mist_api_v2.models.tag_name import TagName  # noqa: E501

class TagFull(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, tag=None, resources=None):  # noqa: E501
        """TagFull - a model defined in OpenAPI

        :param id: The id of this TagFull.  # noqa: E501
        :type id: str
        :param tag: The tag of this TagFull.  # noqa: E501
        :type tag: TagName
        :param resources: The resources of this TagFull.  # noqa: E501
        :type resources: List[ResourceIds]
        """
        self.openapi_types = {
            'id': str,
            'tag': TagName,
            'resources': List[ResourceIds]
        }

        self.attribute_map = {
            'id': 'id',
            'tag': 'tag',
            'resources': 'resources'
        }

        self._id = id
        self._tag = tag
        self._resources = resources

    @classmethod
    def from_dict(cls, dikt) -> 'TagFull':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TagFull of this TagFull.  # noqa: E501
        :rtype: TagFull
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this TagFull.


        :return: The id of this TagFull.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TagFull.


        :param id: The id of this TagFull.
        :type id: str
        """

        self._id = id

    @property
    def tag(self):
        """Gets the tag of this TagFull.


        :return: The tag of this TagFull.
        :rtype: TagName
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this TagFull.


        :param tag: The tag of this TagFull.
        :type tag: TagName
        """

        self._tag = tag

    @property
    def resources(self):
        """Gets the resources of this TagFull.


        :return: The resources of this TagFull.
        :rtype: List[ResourceIds]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this TagFull.


        :param resources: The resources of this TagFull.
        :type resources: List[ResourceIds]
        """

        self._resources = resources
