# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.tag_resources_request_resources import TagResourcesRequestResources
from mist_api_v2 import util

from mist_api_v2.models.tag_resources_request_resources import TagResourcesRequestResources  # noqa: E501

class TagResourcesRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, resources=None):  # noqa: E501
        """TagResourcesRequest - a model defined in OpenAPI

        :param resources: The resources of this TagResourcesRequest.  # noqa: E501
        :type resources: List[TagResourcesRequestResources]
        """
        self.openapi_types = {
            'resources': List[TagResourcesRequestResources]
        }

        self.attribute_map = {
            'resources': 'resources'
        }

        self._resources = resources

    @classmethod
    def from_dict(cls, dikt) -> 'TagResourcesRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TagResourcesRequest of this TagResourcesRequest.  # noqa: E501
        :rtype: TagResourcesRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resources(self):
        """Gets the resources of this TagResourcesRequest.


        :return: The resources of this TagResourcesRequest.
        :rtype: List[TagResourcesRequestResources]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this TagResourcesRequest.


        :param resources: The resources of this TagResourcesRequest.
        :type resources: List[TagResourcesRequestResources]
        """

        self._resources = resources
