# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from mist_api_v2.models.base_model_ import Model
from mist_api_v2.models.when_all_of import WhenAllOf
from mist_api_v2 import util

from mist_api_v2.models.when_all_of import WhenAllOf  # noqa: E501

class When(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, schedule_type=None, datetime=None, minute=None, hour=None, day_of_month=None, month_of_year=None, day_of_week=None, max_run_count=None, every=None, period=None):  # noqa: E501
        """When - a model defined in OpenAPI

        :param schedule_type: The schedule_type of this When.  # noqa: E501
        :type schedule_type: str
        :param datetime: The datetime of this When.  # noqa: E501
        :type datetime: str
        :param minute: The minute of this When.  # noqa: E501
        :type minute: str
        :param hour: The hour of this When.  # noqa: E501
        :type hour: str
        :param day_of_month: The day_of_month of this When.  # noqa: E501
        :type day_of_month: str
        :param month_of_year: The month_of_year of this When.  # noqa: E501
        :type month_of_year: str
        :param day_of_week: The day_of_week of this When.  # noqa: E501
        :type day_of_week: str
        :param max_run_count: The max_run_count of this When.  # noqa: E501
        :type max_run_count: int
        :param every: The every of this When.  # noqa: E501
        :type every: int
        :param period: The period of this When.  # noqa: E501
        :type period: str
        """
        self.openapi_types = {
            'schedule_type': str,
            'datetime': str,
            'minute': str,
            'hour': str,
            'day_of_month': str,
            'month_of_year': str,
            'day_of_week': str,
            'max_run_count': int,
            'every': int,
            'period': str
        }

        self.attribute_map = {
            'schedule_type': 'schedule_type',
            'datetime': 'datetime',
            'minute': 'minute',
            'hour': 'hour',
            'day_of_month': 'day_of_month',
            'month_of_year': 'month_of_year',
            'day_of_week': 'day_of_week',
            'max_run_count': 'max_run_count',
            'every': 'every',
            'period': 'period'
        }

        self._schedule_type = schedule_type
        self._datetime = datetime
        self._minute = minute
        self._hour = hour
        self._day_of_month = day_of_month
        self._month_of_year = month_of_year
        self._day_of_week = day_of_week
        self._max_run_count = max_run_count
        self._every = every
        self._period = period

    @classmethod
    def from_dict(cls, dikt) -> 'When':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The When of this When.  # noqa: E501
        :rtype: When
        """
        return util.deserialize_model(dikt, cls)

    @property
    def schedule_type(self):
        """Gets the schedule_type of this When.


        :return: The schedule_type of this When.
        :rtype: str
        """
        return self._schedule_type

    @schedule_type.setter
    def schedule_type(self, schedule_type):
        """Sets the schedule_type of this When.


        :param schedule_type: The schedule_type of this When.
        :type schedule_type: str
        """
        allowed_values = ["crontab", "interval", "one_off"]  # noqa: E501
        if schedule_type not in allowed_values:
            raise ValueError(
                "Invalid value for `schedule_type` ({0}), must be one of {1}"
                .format(schedule_type, allowed_values)
            )

        self._schedule_type = schedule_type

    @property
    def datetime(self):
        """Gets the datetime of this When.

        When one_off schedule should run, e.g 2021-09-22T18:19:28Z  # noqa: E501

        :return: The datetime of this When.
        :rtype: str
        """
        return self._datetime

    @datetime.setter
    def datetime(self, datetime):
        """Sets the datetime of this When.

        When one_off schedule should run, e.g 2021-09-22T18:19:28Z  # noqa: E501

        :param datetime: The datetime of this When.
        :type datetime: str
        """
        if datetime is None:
            raise ValueError("Invalid value for `datetime`, must not be `None`")  # noqa: E501

        self._datetime = datetime

    @property
    def minute(self):
        """Gets the minute of this When.


        :return: The minute of this When.
        :rtype: str
        """
        return self._minute

    @minute.setter
    def minute(self, minute):
        """Sets the minute of this When.


        :param minute: The minute of this When.
        :type minute: str
        """
        if minute is None:
            raise ValueError("Invalid value for `minute`, must not be `None`")  # noqa: E501

        self._minute = minute

    @property
    def hour(self):
        """Gets the hour of this When.


        :return: The hour of this When.
        :rtype: str
        """
        return self._hour

    @hour.setter
    def hour(self, hour):
        """Sets the hour of this When.


        :param hour: The hour of this When.
        :type hour: str
        """
        if hour is None:
            raise ValueError("Invalid value for `hour`, must not be `None`")  # noqa: E501

        self._hour = hour

    @property
    def day_of_month(self):
        """Gets the day_of_month of this When.


        :return: The day_of_month of this When.
        :rtype: str
        """
        return self._day_of_month

    @day_of_month.setter
    def day_of_month(self, day_of_month):
        """Sets the day_of_month of this When.


        :param day_of_month: The day_of_month of this When.
        :type day_of_month: str
        """
        if day_of_month is None:
            raise ValueError("Invalid value for `day_of_month`, must not be `None`")  # noqa: E501

        self._day_of_month = day_of_month

    @property
    def month_of_year(self):
        """Gets the month_of_year of this When.


        :return: The month_of_year of this When.
        :rtype: str
        """
        return self._month_of_year

    @month_of_year.setter
    def month_of_year(self, month_of_year):
        """Sets the month_of_year of this When.


        :param month_of_year: The month_of_year of this When.
        :type month_of_year: str
        """
        if month_of_year is None:
            raise ValueError("Invalid value for `month_of_year`, must not be `None`")  # noqa: E501

        self._month_of_year = month_of_year

    @property
    def day_of_week(self):
        """Gets the day_of_week of this When.


        :return: The day_of_week of this When.
        :rtype: str
        """
        return self._day_of_week

    @day_of_week.setter
    def day_of_week(self, day_of_week):
        """Sets the day_of_week of this When.


        :param day_of_week: The day_of_week of this When.
        :type day_of_week: str
        """
        if day_of_week is None:
            raise ValueError("Invalid value for `day_of_week`, must not be `None`")  # noqa: E501

        self._day_of_week = day_of_week

    @property
    def max_run_count(self):
        """Gets the max_run_count of this When.


        :return: The max_run_count of this When.
        :rtype: int
        """
        return self._max_run_count

    @max_run_count.setter
    def max_run_count(self, max_run_count):
        """Sets the max_run_count of this When.


        :param max_run_count: The max_run_count of this When.
        :type max_run_count: int
        """
        if max_run_count is not None and max_run_count < 1:  # noqa: E501
            raise ValueError("Invalid value for `max_run_count`, must be a value greater than or equal to `1`")  # noqa: E501

        self._max_run_count = max_run_count

    @property
    def every(self):
        """Gets the every of this When.


        :return: The every of this When.
        :rtype: int
        """
        return self._every

    @every.setter
    def every(self, every):
        """Sets the every of this When.


        :param every: The every of this When.
        :type every: int
        """
        if every is None:
            raise ValueError("Invalid value for `every`, must not be `None`")  # noqa: E501

        self._every = every

    @property
    def period(self):
        """Gets the period of this When.


        :return: The period of this When.
        :rtype: str
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this When.


        :param period: The period of this When.
        :type period: str
        """
        allowed_values = ["minutes", "hours", "days"]  # noqa: E501
        if period not in allowed_values:
            raise ValueError(
                "Invalid value for `period` ({0}), must be one of {1}"
                .format(period, allowed_values)
            )

        self._period = period
