openapi: 3.0.3
info:
  contact:
    email: api@mist.io
    name: Mist API Team
  title: Mist API
  version: 2.0.0
  x-cli-name: Mist CLI
servers:
- description: Mist Hosted Service
  url: https://mist.io/
paths:
  /api/v2/clouds:
    get:
      description: List clouds owned by the active org. READ permission required on
        cloud.
      operationId: list_clouds
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: List clouds
      tags:
      - clouds
      x-cli-table-default:
      - name
      - provider
      - tags
      x-cli-table-extended:
      - id
      - name
      - provider
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
    post:
      description: Adds a new cloud and returns the cloud's id. ADD permission required
        on cloud.
      operationId: add_cloud
      security:
      - ApiKeyAuth:
        - add:cloud
      - CookieAuth:
        - add:cloud
      summary: Add cloud
      tags:
      - clouds
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
  /api/v2/clouds/{cloud}:
    delete:
      description: Delete target cloud
      operationId: delete_cloud
      security:
      - ApiKeyAuth:
        - delete:cloud
      - CookieAuth:
        - delete:cloud
      summary: Delete cloud
      tags:
      - clouds
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
    get:
      description: Get details about target cloud
      operationId: get_cloud
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: Get cloud
      tags:
      - clouds
      x-cli-table-default:
      - name
      - provider
      - tags
      x-cli-table-extended:
      - id
      - name
      - provider
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
    put:
      description: Update target cloud title or credentials
      operationId: edit_cloud
      security:
      - ApiKeyAuth:
        - edit:cloud
      - CookieAuth:
        - edit:cloud
      summary: Edit cloud
      tags:
      - clouds
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
  /api/v2/images:
    get:
      description: List images owned by the active org. READ permission required on
        image & cloud.
      operationId: list_images
      security:
      - ApiKeyAuth:
        - read:image
        - read:cloud
      - CookieAuth:
        - read:image
        - read:cloud
      summary: List images
      tags:
      - images
      x-cli-table-default:
      - starred
      - name
      - cloud
      - os_type
      - tags
      x-cli-table-extended:
      - starred
      - id
      - external_id
      - name
      - cloud
      - os_type
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.images_controller
  /api/v2/images/{image}:
    get:
      description: Get details about target image
      operationId: get_image
      security:
      - ApiKeyAuth:
        - read:image
        - read:cloud
      - CookieAuth:
        - read:image
        - read:cloud
      summary: Get image
      tags:
      - images
      x-cli-table-default:
      - starred
      - name
      - cloud
      - os_type
      - tags
      x-cli-table-extended:
      - starred
      - id
      - external_id
      - name
      - cloud
      - os_type
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.images_controller
  /api/v2/keys:
    get:
      description: List keys owned by the active org. READ permission required on
        key.
      operationId: list_keys
      security:
      - ApiKeyAuth:
        - read:key
      - CookieAuth:
        - read:key
      summary: List keys
      tags:
      - keys
      x-cli-table-default:
      - name
      - default
      - tags
      x-cli-table-extended:
      - id
      - name
      - default
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
    post:
      description: Adds a new key and returns the key's id. ADD permission required
        on key.
      operationId: add_key
      security:
      - ApiKeyAuth:
        - add:key
      - CookieAuth:
        - add:key
      summary: Add key
      tags:
      - keys
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
  /api/v2/keys/{key}:
    delete:
      description: Delete target key
      operationId: delete_key
      security:
      - ApiKeyAuth:
        - delete:key
      - CookieAuth:
        - delete:key
      summary: Delete key
      tags:
      - keys
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
    get:
      description: Get details about target key
      operationId: get_key
      security:
      - ApiKeyAuth:
        - read:key
      - CookieAuth:
        - read:key
      summary: Get key
      tags:
      - keys
      x-cli-table-default:
      - name
      - default
      - tags
      x-cli-table-extended:
      - id
      - name
      - default
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
    put:
      description: Edit target key
      operationId: edit_key
      security:
      - ApiKeyAuth:
        - edit:key
      - CookieAuth:
        - edit:key
      summary: Edit key
      tags:
      - keys
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
  /api/v2/locations:
    get:
      description: List locations owned by the active org. READ permission required
        on location & cloud.
      operationId: list_locations
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: List locations
      tags:
      - locations
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.locations_controller
  /api/v2/locations/{location}:
    get:
      description: Get details about target location
      operationId: get_location
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: Get location
      tags:
      - locations
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - locations
      - external_id
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.locations_controller
  /api/v2/machines:
    get:
      description: List machines owned by the active org. READ permission required
        on machine & cloud.
      operationId: list_machines
      security:
      - ApiKeyAuth:
        - read:machine
        - read:cloud
      - CookieAuth:
        - read:machine
        - read:cloud
      summary: List machines
      tags:
      - machines
      x-cli-table-default:
      - name
      - cloud
      - state
      - tags
      x-cli-table-extended:
      - id
      - name
      - state
      - cloud
      - external_id
      - public_ips
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
    post:
      description: Creates one or more machines on the specified cloud. If async is
        true, a jobId will be returned. READ permission required on cloud. CREATE_RESOURCES
        permission required on cloud. READ permission required on location. CREATE_RESOURCES
        permission required on location. CREATE permission required on machine. RUN
        permission required on script. READ permission required on key.
      operationId: create_machine
      security:
      - ApiKeyAuth:
        - create:machine
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
        - read:image
        - create_resources:image
        - read:script
        - read:key
      - CookieAuth:
        - create:machine
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
        - read:image
        - create_resources:image
        - read:script
        - read:key
      summary: Create machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}:
    get:
      description: Get details about target machine
      operationId: get_machine
      security:
      - ApiKeyAuth:
        - read:machine
        - read:cloud
      - CookieAuth:
        - read:machine
        - read:cloud
      summary: Get machine
      tags:
      - machines
      x-cli-table-default:
      - name
      - cloud
      - state
      - tags
      x-cli-table-extended:
      - id
      - name
      - state
      - cloud
      - external_id
      - public_ips
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
    put:
      description: Edit target machine
      operationId: edit_machine
      security:
      - ApiKeyAuth:
        - edit:machine
      - CookieAuth:
        - edit:machine
      summary: Edit machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/clone:
    post:
      description: Clone target machine
      operationId: clone_machine
      security:
      - ApiKeyAuth:
        - clone:machine
      - CookieAuth:
        - clone:machine
      summary: Clone machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/console:
    post:
      description: Open VNC console on target machine
      operationId: console
      security:
      - ApiKeyAuth:
        - console:machine
      - CookieAuth:
        - console:machine
      summary: Open console
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/destroy:
    post:
      description: Destroy target machine
      operationId: destroy_machine
      security:
      - ApiKeyAuth:
        - destroy:machine
      - CookieAuth:
        - destroy:machine
      summary: Destroy machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/expose:
    post:
      description: Expose target machine
      operationId: expose_machine
      security:
      - ApiKeyAuth:
        - expose:machine
      - CookieAuth:
        - expose:machine
      summary: Expose machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/reboot:
    post:
      description: Reboot target machine
      operationId: reboot_machine
      security:
      - ApiKeyAuth:
        - reboot:machine
      - CookieAuth:
        - reboot:machine
      summary: Reboot machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/rename:
    post:
      description: Rename target machine
      operationId: rename_machine
      security:
      - ApiKeyAuth:
        - rename:machine
      - CookieAuth:
        - rename:machine
      summary: Rename machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/resize:
    post:
      description: Resize target machine
      operationId: resize_machine
      security:
      - ApiKeyAuth:
        - resize:machine
      - CookieAuth:
        - resize:machine
      summary: Resize machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/resume:
    post:
      description: Resume target machine
      operationId: resume_machine
      security:
      - ApiKeyAuth:
        - resume:machine
      - CookieAuth:
        - resume:machine
      summary: Resume machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/ssh:
    post:
      description: Open secure shell on target machine
      operationId: ssh
      security:
      - ApiKeyAuth:
        - read:cloud
        - read:machine
        - ssh:machine
      - CookieAuth:
        - read:cloud
        - read:machine
        - ssh:machine
      summary: Open secure shell
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
    x-cli-ignore: true
  /api/v2/machines/{machine}/actions/start:
    post:
      description: Start target machine
      operationId: start_machine
      security:
      - ApiKeyAuth:
        - start:machine
      - CookieAuth:
        - start:machine
      summary: Start machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/stop:
    post:
      description: Stop target machine
      operationId: stop_machine
      security:
      - ApiKeyAuth:
        - stop:machine
      - CookieAuth:
        - stop:machine
      summary: Stop machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/suspend:
    post:
      description: Suspend target machine
      operationId: suspend_machine
      security:
      - ApiKeyAuth:
        - suspend:machine
      - CookieAuth:
        - suspend:machine
      summary: Suspend machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/undefine:
    post:
      description: Undefine target machine
      operationId: undefine_machine
      security:
      - ApiKeyAuth:
        - undefine:machine
      - CookieAuth:
        - undefine:machine
      summary: Undefine machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/snapshots:
    get:
      description: List snapshots of target machine
      operationId: list_snapshots
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
      summary: Suspend machine
      tags:
      - snapshots
      x-openapi-router-controller: mist_api_v2.controllers.snapshots_controller
    post:
      description: Create snapshots of target machine
      operationId: create_snapshot
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      summary: Create snapshot
      tags:
      - snapshots
      x-openapi-router-controller: mist_api_v2.controllers.snapshots_controller
  /api/v2/machines/{machine}/snapshots/{snapshot}:
    delete:
      description: Remove target machine snapshot
      operationId: remove_snapshot
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      summary: Remove snapshot
      tags:
      - snapshots
      x-openapi-router-controller: mist_api_v2.controllers.snapshots_controller
    post:
      description: Revert machine to snapshot
      operationId: revert_to_snapshot
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
        - revert_to_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
        - revert_to_snapshots:machine
      summary: Revert to snapshot
      tags:
      - snapshots
      x-openapi-router-controller: mist_api_v2.controllers.snapshots_controller
  /api/v2/networks:
    get:
      description: List networks owned by the active org. READ permission required
        on network & cloud.
      operationId: list_networks
      security:
      - ApiKeyAuth:
        - read:network
        - read:cloud
      - CookieAuth:
        - read:network
        - read:cloud
      summary: List networks
      tags:
      - networks
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.networks_controller
    post:
      description: Creates one or more networks on the specified cloud. If async is
        true, a jobId will be returned. READ permission required on cloud. CREATE_RESOURCES
        permission required on cloud. CREATE permission required on network.
      operationId: create_network
      security:
      - ApiKeyAuth:
        - create:network
        - read:cloud
        - create_resources:cloud
      - CookieAuth:
        - create:network
        - read:cloud
        - create_resources:cloud
      summary: Create network
      tags:
      - networks
      x-openapi-router-controller: mist_api_v2.controllers.networks_controller
  /api/v2/networks/{network}:
    get:
      description: Get details about target network
      operationId: get_network
      security:
      - ApiKeyAuth:
        - read:network
        - read:cloud
      - CookieAuth:
        - read:network
        - read:cloud
      summary: Get network
      tags:
      - networks
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - location
      - external_id
      - subnets
      - machines
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.networks_controller
    put:
      description: Edit target network
      operationId: edit_network
      security:
      - ApiKeyAuth:
        - edit:network
      - CookieAuth:
        - edit:network
      summary: Edit network
      tags:
      - networks
      x-openapi-router-controller: mist_api_v2.controllers.networks_controller
  /api/v2/rules:
    get:
      description: Return a filtered list of rules
      operationId: list_rules
      security:
      - ApiKeyAuth:
        - read:rule
      - CookieAuth:
        - read:rule
      summary: List rules
      tags:
      - rules
      x-cli-table-default:
      - title
      - queries
      - actions
      - tags
      x-cli-table-extended:
      - id
      - title
      - resource_type
      - selectors
      - queries
      - actions
      - window
      - frequency
      - tags
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    post:
      description: Add a new rule, READ permission required on target resource, ADD
        permission required on Rule
      operationId: add_rule
      security:
      - ApiKeyAuth:
        - add:rule
      - CookieAuth:
        - add:rule
      summary: Add rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
  /api/v2/rules/{rule}:
    delete:
      description: Delete a rule given its UUID.
      operationId: delete_rule
      security:
      - ApiKeyAuth:
        - delete:rule
      - CookieAuth:
        - delete:rule
      summary: Delete rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    get:
      description: Get details about target rule
      operationId: get_rule
      security:
      - ApiKeyAuth:
        - read:rule
      - CookieAuth:
        - read:rule
      summary: Get rule
      tags:
      - rules
      x-cli-table-default:
      - title
      - queries
      - actions
      - tags
      x-cli-table-extended:
      - id
      - title
      - resource_type
      - selectors
      - queries
      - actions
      - window
      - frequency
      - tags
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    patch:
      description: Rename a rule
      operationId: rename_rule
      security:
      - ApiKeyAuth:
        - write:rule
      - CookieAuth:
        - write:rule
      summary: Rename rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    post:
      description: Update a rule given its UUID, EDIT permission required on rule
      operationId: update_rule
      security:
      - ApiKeyAuth:
        - read:cloud
        - edit:rule
      - CookieAuth:
        - read:cloud
        - edit:rule
      summary: Update rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    put:
      description: Enable or disable a rule
      operationId: toggle_rule
      security:
      - ApiKeyAuth:
        - write:rule
      - CookieAuth:
        - write:rule
      summary: Toggle rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
  /api/v2/scripts:
    get:
      description: List scripts owned by the active org. READ permission required
        on script.
      operationId: list_scripts
      security:
      - ApiKeyAuth:
        - read:script
      - CookieAuth:
        - read:script
      summary: List scripts
      tags:
      - scripts
      x-cli-table-default:
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - description
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
  /api/v2/scripts/{script}:
    delete:
      description: Delete target script
      operationId: delete_script
      security:
      - ApiKeyAuth:
        - delete:script
      - CookieAuth:
        - delete:script
      summary: Delete script
      tags:
      - scripts
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
    get:
      description: Get details about target script
      operationId: get_script
      security:
      - ApiKeyAuth:
        - read:script
      - CookieAuth:
        - read:script
      summary: Get script
      tags:
      - scripts
      x-cli-table-default:
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - description
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
    put:
      description: Edit target script
      operationId: edit_script
      security:
      - ApiKeyAuth:
        - edit:script
      - CookieAuth:
        - edit:script
      summary: Edit script
      tags:
      - scripts
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
  /api/v2/secrets:
    get:
      description: List secrets owned by the active org. READ permission required
        on secret.
      operationId: list_secrets
      security:
      - ApiKeyAuth:
        - read:secret
      - CookieAuth:
        - read:secret
      summary: List secrets
      tags:
      - secrets
      x-cli-table-default:
      - id
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
    post:
      description: Creates a new secret and returns the secret's id. CREATE permission
        required on secret.
      operationId: create_secret
      security:
      - ApiKeyAuth:
        - create:secret
      - CookieAuth:
        - create:secret
      summary: Create secret
      tags:
      - secrets
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
  /api/v2/secrets/{secret}:
    delete:
      description: Delete target secret
      operationId: delete_secret
      security:
      - ApiKeyAuth:
        - delete:secret
      - CookieAuth:
        - delete:secret
      summary: Delete secret
      tags:
      - secrets
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
    get:
      description: Read target secret
      operationId: get_secret
      security:
      - ApiKeyAuth:
        - read:secret
      - CookieAuth:
        - read:secret
      summary: Get secret
      tags:
      - secrets
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
    put:
      description: Edit/update target secret
      operationId: edit_secret
      security:
      - ApiKeyAuth:
        - edit:secret
      - CookieAuth:
        - edit:secret
      summary: Edit secret
      tags:
      - secrets
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
  /api/v2/sizes:
    get:
      description: List sizes owned by the active org. READ permission required on
        size & cloud.
      operationId: list_sizes
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: List sizes
      tags:
      - sizes
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.sizes_controller
  /api/v2/sizes/{size}:
    get:
      description: Get details about target size
      operationId: get_size
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: Get size
      tags:
      - sizes
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - locations
      - external_id
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.sizes_controller
  /api/v2/volumes:
    get:
      description: List volumes owned by the active org. READ permission required
        on volume & cloud.
      operationId: list_volumes
      security:
      - ApiKeyAuth:
        - read:volume
        - read:cloud
      - CookieAuth:
        - read:volume
        - read:cloud
      summary: List volumes
      tags:
      - volumes
      x-cli-table-default:
      - name
      - size
      - cloud
      - location
      - attached_to
      - tags
      x-cli-table-extended:
      - id
      - name
      - size
      - cloud
      - location
      - external_id
      - attached_to
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.volumes_controller
    post:
      description: Creates one or more volumes on the specified cloud. If async is
        true, a jobId will be returned. READ permission required on cloud. CREATE_RESOURCES
        permission required on cloud. READ permission required on location. CREATE_RESOURCES
        permission required on location. CREATE permission required on volume.
      operationId: create_volume
      security:
      - ApiKeyAuth:
        - create:volume
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
      - CookieAuth:
        - create:volume
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
      summary: Create volume
      tags:
      - volumes
      x-openapi-router-controller: mist_api_v2.controllers.volumes_controller
  /api/v2/volumes/{volume}:
    get:
      description: Get details about target volume
      operationId: get_volume
      security:
      - ApiKeyAuth:
        - read:volume
        - read:cloud
      - CookieAuth:
        - read:volume
        - read:cloud
      summary: Get volume
      tags:
      - volumes
      x-cli-table-default:
      - name
      - size
      - cloud
      - location
      - attached_to
      - tags
      x-cli-table-extended:
      - id
      - name
      - size
      - cloud
      - location
      - external_id
      - attached_to
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.volumes_controller
    put:
      description: Edit target volume
      operationId: edit_volume
      security:
      - ApiKeyAuth:
        - edit:volume
        - read:cloud
      - CookieAuth:
        - edit:volume
        - read:cloud
      summary: Edit volume
      tags:
      - volumes
      x-openapi-router-controller: mist_api_v2.controllers.volumes_controller
  /api/v2/zones:
    get:
      description: List zones owned by the active org. READ permission required on
        zone & cloud.
      operationId: list_zones
      security:
      - ApiKeyAuth:
        - read:zone
        - read:cloud
      - CookieAuth:
        - read:zone
        - read:cloud
      summary: List zones
      tags:
      - zones
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
    post:
      description: Creates one or more zones on the specified cloud. If async is true,
        a jobId will be returned. READ permission required on cloud. CREATE_RESOURCES
        permission required on cloud. CREATE permission required on zone.
      operationId: create_zone
      security:
      - ApiKeyAuth:
        - create:zone
        - read:cloud
        - create_resources:cloud
      - CookieAuth:
        - create:zone
        - read:cloud
        - create_resources:cloud
      summary: Create zone
      tags:
      - zones
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
  /api/v2/zones/{zone}:
    get:
      description: Get details about target zone
      operationId: get_zone
      security:
      - ApiKeyAuth:
        - read:zone
        - read:cloud
      - CookieAuth:
        - read:zone
        - read:cloud
      summary: Get zone
      tags:
      - zones
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - location
      - external_id
      - subnets
      - machines
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
    put:
      description: Edit target zone
      operationId: edit_zone
      security:
      - ApiKeyAuth:
        - edit:zone
      - CookieAuth:
        - edit:zone
      summary: Edit zone
      tags:
      - zones
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: mist_api_v2.controllers.security_controller_.info_from_ApiKeyAuth
    CookieAuth:
      in: cookie
      name: session.id
      type: apiKey
      x-apikeyInfoFunc: mist_api_v2.controllers.security_controller_.info_from_CookieAuth
