openapi: 3.0.3
info:
  contact:
    email: api@mist.io
    name: Mist API Team
  title: Mist API
  version: 2.0.0
  x-cli-name: Mist CLI
servers:
- description: Mist Hosted Service
  url: https://mist.io/
paths:
  /api/v2/auth:
    get:
      description: Return info about current authenticated session.
      operationId: describe_auth
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: Authentication info
      tags:
      - auth
      x-openapi-router-controller: mist_api_v2.controllers.auth_controller
  /api/v2/auth/sessions:
    get:
      description: Return a list of active sessions
      operationId: list_sessions
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List sessions
      tags:
      - auth
      x-cli-table-default:
      - last_active
      x-cli-table-extended:
      - last_active
      - id
      - creation_date
      x-openapi-router-controller: mist_api_v2.controllers.auth_controller
    post:
      description: Sign in
      operationId: login
      summary: Sign in to the portal
      tags:
      - auth
      x-openapi-router-controller: mist_api_v2.controllers.auth_controller
  /api/v2/auth/tokens:
    get:
      description: List API tokens
      operationId: list_tokens
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List API tokens
      tags:
      - auth
      x-cli-table-default:
      - email
      x-cli-table-extended:
      - email
      - id
      - last_login
      - registration_date
      x-openapi-router-controller: mist_api_v2.controllers.auth_controller
    post:
      description: Create new API token
      operationId: create_token
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: Create token
      tags:
      - auth
      x-openapi-router-controller: mist_api_v2.controllers.auth_controller
  /api/v2/clouds:
    get:
      description: List clouds owned by the active org. READ permission required on
        cloud.
      operationId: list_clouds
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: List clouds
      tags:
      - clouds
      x-cli-table-default:
      - name
      - provider
      - tags
      x-cli-table-extended:
      - id
      - name
      - provider
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
    post:
      description: Adds a new cloud and returns the cloud's id. ADD permission required
        on cloud.
      operationId: add_cloud
      security:
      - ApiKeyAuth:
        - add:cloud
      - CookieAuth:
        - add:cloud
      summary: Add cloud
      tags:
      - clouds
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
  /api/v2/clouds/{cloud}:
    delete:
      description: Remove target cloud
      operationId: remove_cloud
      security:
      - ApiKeyAuth:
        - remove:cloud
      - CookieAuth:
        - remove:cloud
      summary: Remove cloud
      tags:
      - clouds
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
    get:
      description: Get details about target cloud
      operationId: get_cloud
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: Get cloud
      tags:
      - clouds
      x-cli-table-default:
      - name
      - provider
      - tags
      x-cli-table-extended:
      - id
      - name
      - provider
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
    put:
      description: Update target cloud name or credentials
      operationId: edit_cloud
      security:
      - ApiKeyAuth:
        - edit:cloud
      - CookieAuth:
        - edit:cloud
      summary: Edit cloud
      tags:
      - clouds
      x-openapi-router-controller: mist_api_v2.controllers.clouds_controller
  /api/v2/clusters:
    get:
      description: List clusters
      operationId: list_clusters
      security:
      - ApiKeyAuth:
        - read:cluster
        - read:cloud
      - CookieAuth:
        - read:cluster
        - read:cloud
      summary: List clusters
      tags:
      - clusters
      x-cli-table-default:
      - name
      - cloud
      - total_nodes
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - total_nodes
      - total_cpus
      - total_ram
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.clusters_controller
    post:
      description: Create a new cluster and return the cluster's id
      operationId: create_cluster
      security:
      - ApiKeyAuth:
        - create:cluster
        - read:cloud
        - create_resources:cloud
      - CookieAuth:
        - create:cluster
        - read:cloud
        - create_resources:cloud
      summary: Create cluster
      tags:
      - clusters
      x-openapi-router-controller: mist_api_v2.controllers.clusters_controller
  /api/v2/clusters/{cluster}:
    delete:
      description: Destroy target clusters
      operationId: destroy_cluster
      security:
      - ApiKeyAuth:
        - read:cloud
        - destroy:cluster
      - CookieAuth:
        - read:cloud
        - destroy:cluster
      summary: Destroy cluster
      tags:
      - clusters
      x-openapi-router-controller: mist_api_v2.controllers.clusters_controller
    get:
      description: Get details about target cluster
      operationId: get_cluster
      security:
      - ApiKeyAuth:
        - read:cluster
        - read:cloud
      - CookieAuth:
        - read:cluster
        - read:cloud
      summary: Get cluster
      tags:
      - clusters
      x-cli-table-default:
      - name
      - cloud
      - total_nodes
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - total_nodes
      - total_cpus
      - total_ram
      - tags
      - owned_by
      - created_by
      x-cli-table-override:
      - credentials
      x-openapi-router-controller: mist_api_v2.controllers.clusters_controller
  /api/v2/clusters/{cluster}/nodepools/{nodepool}:
    post:
      description: Scale the nodes of the specified nodepool
      operationId: scale_nodepool
      security:
      - ApiKeyAuth:
        - create:cluster
        - read:cloud
        - create_resources:cloud
      - CookieAuth:
        - create:cluster
        - read:cloud
        - create_resources:cloud
      summary: Scale cluster nodepool
      tags:
      - clusters
      x-openapi-router-controller: mist_api_v2.controllers.clusters_controller
  /api/v2/datapoints:
    get:
      description: Get datapoints for a specific query
      operationId: get_datapoints
      security:
      - ApiKeyAuth:
        - read:cloud
        - read:machine
      - CookieAuth:
        - read:cloud
        - read:machine
      summary: Get datapoints
      tags:
      - datapoints
      x-openapi-router-controller: mist_api_v2.controllers.datapoints_controller
  /api/v2/images:
    get:
      description: List images owned by the active org. READ permission required on
        image & cloud.
      operationId: list_images
      security:
      - ApiKeyAuth:
        - read:image
        - read:cloud
      - CookieAuth:
        - read:image
        - read:cloud
      summary: List images
      tags:
      - images
      x-cli-table-default:
      - starred
      - name
      - cloud
      - os_type
      - tags
      x-cli-table-extended:
      - starred
      - id
      - external_id
      - name
      - cloud
      - os_type
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.images_controller
  /api/v2/images/{image}:
    get:
      description: Get details about target image
      operationId: get_image
      security:
      - ApiKeyAuth:
        - read:image
        - read:cloud
      - CookieAuth:
        - read:image
        - read:cloud
      summary: Get image
      tags:
      - images
      x-cli-table-default:
      - starred
      - name
      - cloud
      - os_type
      - tags
      x-cli-table-extended:
      - starred
      - id
      - external_id
      - name
      - cloud
      - os_type
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.images_controller
  /api/v2/jobs/{job_id}:
    get:
      operationId: get_job
      security:
      - ApiKeyAuth:
        - read:job
      - CookieAuth:
        - read:job
      summary: Get job
      tags:
      - jobs
      x-openapi-router-controller: mist_api_v2.controllers.jobs_controller
  /api/v2/keys:
    get:
      description: List keys owned by the active org. READ permission required on
        key.
      operationId: list_keys
      security:
      - ApiKeyAuth:
        - read:key
      - CookieAuth:
        - read:key
      summary: List keys
      tags:
      - keys
      x-cli-table-default:
      - name
      - default
      - tags
      x-cli-table-extended:
      - id
      - name
      - default
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
    post:
      description: Adds a new key and returns the key's id. ADD permission required
        on key.
      operationId: add_key
      security:
      - ApiKeyAuth:
        - add:key
      - CookieAuth:
        - add:key
      summary: Add key
      tags:
      - keys
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
  /api/v2/keys/{key}:
    delete:
      description: Delete target key
      operationId: delete_key
      security:
      - ApiKeyAuth:
        - delete:key
      - CookieAuth:
        - delete:key
      summary: Delete key
      tags:
      - keys
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
    get:
      description: Get details about target key
      operationId: get_key
      security:
      - ApiKeyAuth:
        - read:key
      - CookieAuth:
        - read:key
      summary: Get key
      tags:
      - keys
      x-cli-table-default:
      - name
      - default
      - tags
      x-cli-table-extended:
      - id
      - name
      - default
      - tags
      - owned_by
      - created_by
      x-cli-table-override:
      - private
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
    put:
      description: Edit target key
      operationId: edit_key
      security:
      - ApiKeyAuth:
        - edit:key
      - CookieAuth:
        - edit:key
      summary: Edit key
      tags:
      - keys
      x-openapi-router-controller: mist_api_v2.controllers.keys_controller
  /api/v2/locations:
    get:
      description: List locations owned by the active org. READ permission required
        on location & cloud.
      operationId: list_locations
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: List locations
      tags:
      - locations
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.locations_controller
  /api/v2/locations/{location}:
    get:
      description: Get details about target location
      operationId: get_location
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: Get location
      tags:
      - locations
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - locations
      - external_id
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.locations_controller
  /api/v2/machines:
    get:
      description: List machines owned by the active org. READ permission required
        on machine & cloud.
      operationId: list_machines
      security:
      - ApiKeyAuth:
        - read:machine
        - read:cloud
      - CookieAuth:
        - read:machine
        - read:cloud
      summary: List machines
      tags:
      - machines
      x-cli-table-default:
      - name
      - cloud
      - state
      - tags
      x-cli-table-extended:
      - id
      - name
      - state
      - cloud
      - external_id
      - public_ips
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
    post:
      description: "Creates one or more machines on the specified cloud. If async\
        \ is true, a jobId will be returned.\nREAD permission required on cloud. CREATE_RESOURCES\
        \ permission required on cloud. READ permission required on location.\nCREATE_RESOURCES\
        \ permission required on location. CREATE permission required on machine.\
        \ RUN permission required on script. READ permission required on key.\n"
      operationId: create_machine
      security:
      - ApiKeyAuth:
        - create:machine
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
        - read:image
        - create_resources:image
        - read:script
        - read:key
      - CookieAuth:
        - create:machine
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
        - read:image
        - create_resources:image
        - read:script
        - read:key
      summary: Create machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}:
    get:
      description: Get details about target machine
      operationId: get_machine
      security:
      - ApiKeyAuth:
        - read:machine
        - read:cloud
      - CookieAuth:
        - read:machine
        - read:cloud
      summary: Get machine
      tags:
      - machines
      x-cli-table-default:
      - name
      - cloud
      - state
      - tags
      x-cli-table-extended:
      - id
      - name
      - state
      - cloud
      - external_id
      - public_ips
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
    put:
      description: Edit target machine
      operationId: edit_machine
      security:
      - ApiKeyAuth:
        - edit:machine
      - CookieAuth:
        - edit:machine
      summary: Edit machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/associate-key:
    put:
      description: Associate a key with a machine.
      operationId: associate_key
      security:
      - ApiKeyAuth:
        - associate_key:machine
        - read:cloud
        - read_private:key
      - CookieAuth:
        - associate_key:machine
        - read:cloud
        - read_private:key
      summary: Associate a key with a machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/clone:
    post:
      description: Clone target machine
      operationId: clone_machine
      security:
      - ApiKeyAuth:
        - clone:machine
      - CookieAuth:
        - clone:machine
      summary: Clone machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/console:
    post:
      description: Open VNC console on target machine
      operationId: console
      security:
      - ApiKeyAuth:
        - console:machine
      - CookieAuth:
        - console:machine
      summary: Open console
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
    x-cli-ignore: true
  /api/v2/machines/{machine}/actions/destroy:
    post:
      description: Destroy target machine
      operationId: destroy_machine
      security:
      - ApiKeyAuth:
        - destroy:machine
      - CookieAuth:
        - destroy:machine
      summary: Destroy machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/disassociate-key:
    delete:
      description: Disassociate a key from a machine.
      operationId: disassociate_key
      security:
      - ApiKeyAuth:
        - disassociate_key:machine
        - read:cloud
      - CookieAuth:
        - disassociate_key:machine
        - read:cloud
      summary: Disassociate a key from a machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/reboot:
    post:
      description: Reboot target machine
      operationId: reboot_machine
      security:
      - ApiKeyAuth:
        - reboot:machine
      - CookieAuth:
        - reboot:machine
      summary: Reboot machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/rename:
    post:
      description: Rename target machine
      operationId: rename_machine
      security:
      - ApiKeyAuth:
        - rename:machine
      - CookieAuth:
        - rename:machine
      summary: Rename machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/resize:
    post:
      description: Resize target machine
      operationId: resize_machine
      security:
      - ApiKeyAuth:
        - resize:machine
      - CookieAuth:
        - resize:machine
      summary: Resize machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/resume:
    post:
      description: Resume target machine
      operationId: resume_machine
      security:
      - ApiKeyAuth:
        - resume:machine
      - CookieAuth:
        - resume:machine
      summary: Resume machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/ssh:
    post:
      description: Open secure shell on target machine
      operationId: ssh
      security:
      - ApiKeyAuth:
        - read:cloud
        - read:machine
        - ssh:machine
      - CookieAuth:
        - read:cloud
        - read:machine
        - ssh:machine
      summary: Open secure shell
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
    x-cli-ignore: true
  /api/v2/machines/{machine}/actions/start:
    post:
      description: Start target machine
      operationId: start_machine
      security:
      - ApiKeyAuth:
        - start:machine
      - CookieAuth:
        - start:machine
      summary: Start machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/stop:
    post:
      description: Stop target machine
      operationId: stop_machine
      security:
      - ApiKeyAuth:
        - stop:machine
      - CookieAuth:
        - stop:machine
      summary: Stop machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/suspend:
    post:
      description: Suspend target machine
      operationId: suspend_machine
      security:
      - ApiKeyAuth:
        - suspend:machine
      - CookieAuth:
        - suspend:machine
      summary: Suspend machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/actions/undefine:
    post:
      description: Undefine target machine
      operationId: undefine_machine
      security:
      - ApiKeyAuth:
        - undefine:machine
      - CookieAuth:
        - undefine:machine
      summary: Undefine machine
      tags:
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.machines_controller
  /api/v2/machines/{machine}/snapshots:
    get:
      description: List snapshots of target machine
      operationId: list_snapshots
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
      summary: List machine snapshots
      tags:
      - snapshots
      x-openapi-router-controller: mist_api_v2.controllers.snapshots_controller
    post:
      description: Create snapshots of target machine
      operationId: create_snapshot
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      summary: Create snapshot
      tags:
      - snapshots
      x-openapi-router-controller: mist_api_v2.controllers.snapshots_controller
  /api/v2/machines/{machine}/snapshots/{snapshot}:
    delete:
      description: Remove target machine snapshot
      operationId: remove_snapshot
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      summary: Remove snapshot
      tags:
      - snapshots
      x-openapi-router-controller: mist_api_v2.controllers.snapshots_controller
    post:
      description: Revert machine to snapshot
      operationId: revert_to_snapshot
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
        - revert_to_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
        - revert_to_snapshots:machine
      summary: Revert to snapshot
      tags:
      - snapshots
      x-openapi-router-controller: mist_api_v2.controllers.snapshots_controller
  /api/v2/networks:
    get:
      description: List networks owned by the active org. READ permission required
        on network & cloud.
      operationId: list_networks
      security:
      - ApiKeyAuth:
        - read:network
        - read:cloud
      - CookieAuth:
        - read:network
        - read:cloud
      summary: List networks
      tags:
      - networks
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.networks_controller
    post:
      description: "Creates one or more networks on the specified cloud. If async\
        \ is true, a jobId will be returned.\nREAD permission required on cloud. CREATE_RESOURCES\
        \ permission required on cloud. CREATE permission required on network.\n"
      operationId: create_network
      security:
      - ApiKeyAuth:
        - create:network
        - read:cloud
        - create_resources:cloud
      - CookieAuth:
        - create:network
        - read:cloud
        - create_resources:cloud
      summary: Create network
      tags:
      - networks
      x-openapi-router-controller: mist_api_v2.controllers.networks_controller
  /api/v2/networks/{network}:
    delete:
      description: Delete target network
      operationId: delete_network
      security:
      - ApiKeyAuth:
        - read:cloud
        - read:network
        - remove:network
      - CookieAuth:
        - read:cloud
        - read:network
        - remove:network
      summary: Delete network
      tags:
      - networks
      x-openapi-router-controller: mist_api_v2.controllers.networks_controller
    get:
      description: Get details about target network
      operationId: get_network
      security:
      - ApiKeyAuth:
        - read:network
        - read:cloud
      - CookieAuth:
        - read:network
        - read:cloud
      summary: Get network
      tags:
      - networks
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - location
      - external_id
      - subnets
      - machines
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.networks_controller
    put:
      description: Edit target network
      operationId: edit_network
      security:
      - ApiKeyAuth:
        - edit:network
      - CookieAuth:
        - edit:network
      summary: Edit network
      tags:
      - networks
      x-openapi-router-controller: mist_api_v2.controllers.networks_controller
  /api/v2/orgs:
    get:
      description: List orgs owned by the requester. If parameter allorgs is true
        and requester is an admin then all orgs will be listed.
      operationId: list_orgs
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List orgs
      tags:
      - orgs
      x-cli-table-default:
      - name
      - clouds_count
      - teams_count
      x-cli-table-extended:
      - name
      - id
      - clouds_count
      - teams_count
      - last_active
      x-openapi-router-controller: mist_api_v2.controllers.orgs_controller
    post:
      description: Create an organization.
      operationId: create_org
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: Create org
      tags:
      - orgs
      x-openapi-router-controller: mist_api_v2.controllers.orgs_controller
    x-cli-ignore: true
  /api/v2/orgs/{org}:
    get:
      description: Get details about target org
      operationId: get_org
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: Get Org
      tags:
      - orgs
      x-cli-table-extended:
      - name
      - id
      - clouds_count
      - total_machine_count
      - last_active
      x-openapi-router-controller: mist_api_v2.controllers.orgs_controller
    patch:
      description: Update organization
      operationId: update_org
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      tags:
      - orgs
      x-openapi-router-controller: mist_api_v2.controllers.orgs_controller
    x-cli-ignore: true
  /api/v2/orgs/{org}/members:
    get:
      description: List org members owned by the requester. The requester must be
        a member of the org.
      operationId: list_org_members
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List org members
      tags:
      - orgs
      x-cli-table-default:
      - email
      x-cli-table-extended:
      - email
      - id
      - last_login
      - registration_date
      x-openapi-router-controller: mist_api_v2.controllers.orgs_controller
    x-cli-ignore: true
  /api/v2/orgs/{org}/members/{member}:
    get:
      description: Get details about target member
      operationId: get_member
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: Get Org
      tags:
      - orgs
      x-cli-table-default:
      - email
      x-cli-table-extended:
      - email
      - id
      - last_login
      - registration_date
      x-openapi-router-controller: mist_api_v2.controllers.orgs_controller
    x-cli-ignore: true
  /api/v2/orgs/{org}/teams:
    get:
      description: List teams in org.
      operationId: list_org_teams
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List org teams
      tags:
      - orgs
      x-cli-table-default:
      - name
      - members_count
      x-cli-table-extended:
      - id
      - name
      - members_count
      - members
      - description
      - policy
      x-openapi-router-controller: mist_api_v2.controllers.orgs_controller
    x-cli-ignore: true
  /api/v2/rules:
    get:
      description: Return a filtered list of rules
      operationId: list_rules
      security:
      - ApiKeyAuth:
        - read:rule
      - CookieAuth:
        - read:rule
      summary: List rules
      tags:
      - rules
      x-cli-table-default:
      - name
      - actions
      - tags
      x-cli-table-extended:
      - id
      - name
      - conditions
      - selectors
      - actions
      - tags
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    post:
      description: "Add a new rule, READ permission required on target resource, ADD\
        \ permission required on Rule"
      operationId: add_rule
      security:
      - ApiKeyAuth:
        - add:rule
      - CookieAuth:
        - add:rule
      summary: Add rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
  /api/v2/rules/{rule}:
    delete:
      description: Delete a rule given its UUID.
      operationId: delete_rule
      security:
      - ApiKeyAuth:
        - delete:rule
      - CookieAuth:
        - delete:rule
      summary: Delete rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    get:
      description: Get details about target rule
      operationId: get_rule
      security:
      - ApiKeyAuth:
        - read:rule
      - CookieAuth:
        - read:rule
      summary: Get rule
      tags:
      - rules
      x-cli-table-default:
      - name
      - actions
      - tags
      x-cli-table-extended:
      - id
      - name
      - conditions
      - selectors
      - actions
      - tags
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    patch:
      description: Rename a rule
      operationId: rename_rule
      security:
      - ApiKeyAuth:
        - write:rule
      - CookieAuth:
        - write:rule
      summary: Rename rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    post:
      description: "Edit a rule given its UUID, EDIT permission required on rule"
      operationId: edit_rule
      security:
      - ApiKeyAuth:
        - read:cloud
        - edit:rule
      - CookieAuth:
        - read:cloud
        - edit:rule
      summary: Update rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
    put:
      description: Enable or disable a rule
      operationId: toggle_rule
      security:
      - ApiKeyAuth:
        - write:rule
      - CookieAuth:
        - write:rule
      summary: Toggle rule
      tags:
      - rules
      x-openapi-router-controller: mist_api_v2.controllers.rules_controller
  /api/v2/schedules:
    get:
      description: List schedules owned by the active org. READ permission required
        on schedules.
      operationId: list_schedules
      security:
      - ApiKeyAuth:
        - read:schedule
      - CookieAuth:
        - read:schedule
      summary: List schedules
      tags:
      - schedules
      x-cli-table-default:
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - description
      - tags
      - enabled
      - actions
      - selectors
      - when
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.schedules_controller
    post:
      description: Add schedule to user schedules
      operationId: add_schedule
      security:
      - ApiKeyAuth:
        - add:schedule
      - CookieAuth:
        - add:schedule
      summary: Add schedule
      tags:
      - schedules
      x-openapi-router-controller: mist_api_v2.controllers.schedules_controller
  /api/v2/schedules/{schedule}:
    delete:
      description: Delete target schedule
      operationId: delete_schedule
      security:
      - ApiKeyAuth:
        - delete:schedule
      - CookieAuth:
        - delete:schedule
      summary: Delete schedule
      tags:
      - schedules
      x-openapi-router-controller: mist_api_v2.controllers.schedules_controller
    get:
      description: Get details about target schedule
      operationId: get_schedule
      security:
      - ApiKeyAuth:
        - read:schedule
      - CookieAuth:
        - read:schedule
      summary: Get schedule
      tags:
      - schedules
      x-cli-table-default:
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - description
      - tags
      - enabled
      - actions
      - selectors
      - when
      - run_immediately
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.schedules_controller
    patch:
      description: Edit target schedule
      operationId: edit_schedule
      security:
      - ApiKeyAuth:
        - edit:schedule
      - CookieAuth:
        - edit:schedule
      summary: Edit schedule
      tags:
      - schedules
      x-openapi-router-controller: mist_api_v2.controllers.schedules_controller
  /api/v2/scripts:
    get:
      description: List scripts owned by the active org. READ permission required
        on script.
      operationId: list_scripts
      security:
      - ApiKeyAuth:
        - read:script
      - CookieAuth:
        - read:script
      summary: List scripts
      tags:
      - scripts
      x-cli-table-default:
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - description
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
    post:
      description: Add script to user scripts
      operationId: add_script
      security:
      - ApiKeyAuth:
        - add:script
      - CookieAuth:
        - add:script
      summary: Add script
      tags:
      - scripts
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
  /api/v2/scripts/{script}:
    delete:
      description: Delete target script
      operationId: delete_script
      security:
      - ApiKeyAuth:
        - delete:script
      - CookieAuth:
        - delete:script
      summary: Delete script
      tags:
      - scripts
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
    get:
      description: Get details about target script
      operationId: get_script
      security:
      - ApiKeyAuth:
        - read:script
      - CookieAuth:
        - read:script
      summary: Get script
      tags:
      - scripts
      x-cli-table-default:
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - description
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
    post:
      description: Start a script job to run the script.
      operationId: run_script
      security:
      - ApiKeyAuth:
        - read:cloud
        - run_script:machine
        - run:script
      - CookieAuth:
        - read:cloud
        - run_script:machine
        - run:script
      summary: Run script
      tags:
      - scripts
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
    put:
      description: Edit target script
      operationId: edit_script
      security:
      - ApiKeyAuth:
        - edit:script
      - CookieAuth:
        - edit:script
      summary: Edit script
      tags:
      - scripts
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
  /api/v2/scripts/{script}/file:
    get:
      description: Download script file or archive
      operationId: download_script
      summary: Download script
      tags:
      - scripts
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
  /api/v2/scripts/{script}/url:
    get:
      description: Generate url for fetching script file
      operationId: generate_script_url
      security:
      - ApiKeyAuth:
        - read:script
      - CookieAuth:
        - read:script
      summary: Generate script url
      tags:
      - scripts
      x-openapi-router-controller: mist_api_v2.controllers.scripts_controller
  /api/v2/secrets:
    get:
      description: List secrets owned by the active org. READ permission required
        on secret.
      operationId: list_secrets
      security:
      - ApiKeyAuth:
        - read:secret
      - CookieAuth:
        - read:secret
      summary: List secrets
      tags:
      - secrets
      x-cli-table-default:
      - id
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
    post:
      description: Creates a new secret and returns the secret's id. CREATE permission
        required on secret.
      operationId: create_secret
      security:
      - ApiKeyAuth:
        - create:secret
      - CookieAuth:
        - create:secret
      summary: Create secret
      tags:
      - secrets
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
  /api/v2/secrets/{secret}:
    delete:
      description: Delete target secret
      operationId: delete_secret
      security:
      - ApiKeyAuth:
        - delete:secret
      - CookieAuth:
        - delete:secret
      summary: Delete secret
      tags:
      - secrets
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
    get:
      description: Read target secret
      operationId: get_secret
      security:
      - ApiKeyAuth:
        - read:secret
      - CookieAuth:
        - read:secret
      summary: Get secret
      tags:
      - secrets
      x-cli-table-default:
      - id
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - tags
      - owned_by
      - created_by
      x-cli-table-override:
      - value
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
    put:
      description: Edit/update target secret
      operationId: edit_secret
      security:
      - ApiKeyAuth:
        - edit:secret
      - CookieAuth:
        - edit:secret
      summary: Edit secret
      tags:
      - secrets
      x-openapi-router-controller: mist_api_v2.controllers.secrets_controller
  /api/v2/sizes:
    get:
      description: List sizes owned by the active org. READ permission required on
        size & cloud.
      operationId: list_sizes
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: List sizes
      tags:
      - sizes
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.sizes_controller
  /api/v2/sizes/{size}:
    get:
      description: Get details about target size
      operationId: get_size
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: Get size
      tags:
      - sizes
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - locations
      - external_id
      - machines
      x-openapi-router-controller: mist_api_v2.controllers.sizes_controller
  /api/v2/tags:
    get:
      description: List tags on resources owned by the active org. READ permission
        required on each resource.
      operationId: list_tags
      security:
      - ApiKeyAuth:
        - read:cluster
        - read:cloud
        - read:image
        - read:key
        - read:machine
        - read:network
        - read:script
        - read:volumes
        - read:zones
      - CookieAuth:
        - read:cluster
        - read:cloud
        - read:image
        - read:key
        - read:machine
        - read:network
        - read:script
        - read:volumes
        - read:zones
      summary: List tags
      tags:
      - tags
      x-cli-table-default:
      - tag
      - buckets
      - clouds
      - clusters
      - images
      - keys
      - machines
      - networks
      - records
      - schedules
      - scripts
      - secrets
      - stacks
      - subnets
      - templates
      - tunnels
      - volumes
      - zones
      - resource_count
      x-cli-table-extended:
      - tag
      - buckets
      - clouds
      - clusters
      - images
      - keys
      - machines
      - networks
      - records
      - schedules
      - scripts
      - secrets
      - stacks
      - subnets
      - templates
      - tunnels
      - volumes
      - zones
      - resource_count
      x-openapi-router-controller: mist_api_v2.controllers.tags_controller
    post:
      description: Batch operation for adding/removing tags from a list of resources.
      operationId: tag_resources
      security:
      - ApiKeyAuth:
        - read:cluster
        - read:cloud
        - read:image
        - read:key
        - read:machine
        - read:network
        - read:script
        - read:volumes
        - read:zones
        - read:cluster
        - edit:cloud
        - edit:image
        - edit:key
        - edit:machine
        - edit:network
        - edit:script
        - edit:volumes
        - edit:zones
      - CookieAuth:
        - read:cluster
        - read:cloud
        - read:image
        - read:key
        - read:machine
        - read:network
        - read:script
        - read:volumes
        - read:zones
        - read:cluster
        - edit:cloud
        - edit:image
        - edit:key
        - edit:machine
        - edit:network
        - edit:script
        - edit:volumes
        - edit:zones
      summary: Tag Resources
      tags:
      - tags
      x-cli-ignore: true
      x-openapi-router-controller: mist_api_v2.controllers.tags_controller
  /api/v2/users:
    get:
      description: Return current user if requester is not admin. Return all users
        for admin.
      operationId: list_users
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List users
      tags:
      - users
      x-cli-table-default:
      - email
      x-cli-table-extended:
      - email
      - id
      - last_login
      - registration_date
      x-openapi-router-controller: mist_api_v2.controllers.users_controller
  /api/v2/volumes:
    get:
      description: List volumes owned by the active org. READ permission required
        on volume & cloud.
      operationId: list_volumes
      security:
      - ApiKeyAuth:
        - read:volume
        - read:cloud
      - CookieAuth:
        - read:volume
        - read:cloud
      summary: List volumes
      tags:
      - volumes
      x-cli-table-default:
      - name
      - size
      - cloud
      - location
      - attached_to
      - tags
      x-cli-table-extended:
      - id
      - name
      - size
      - cloud
      - location
      - external_id
      - attached_to
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.volumes_controller
    post:
      description: "Creates one or more volumes on the specified cloud. If async is\
        \ true, a jobId will be returned.\nREAD permission required on cloud. CREATE_RESOURCES\
        \ permission required on cloud. READ permission required on location.\nCREATE_RESOURCES\
        \ permission required on location. CREATE permission required on volume.\n"
      operationId: create_volume
      security:
      - ApiKeyAuth:
        - create:volume
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
      - CookieAuth:
        - create:volume
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
      summary: Create volume
      tags:
      - volumes
      x-openapi-router-controller: mist_api_v2.controllers.volumes_controller
  /api/v2/volumes/{volume}:
    delete:
      description: Delete target volume
      operationId: delete_volume
      security:
      - ApiKeyAuth:
        - read:volume
        - delete:volume
        - read:cloud
      - CookieAuth:
        - read:volume
        - delete:volume
        - read:cloud
      summary: Delete volume
      tags:
      - volumes
      x-openapi-router-controller: mist_api_v2.controllers.volumes_controller
    get:
      description: Get details about target volume
      operationId: get_volume
      security:
      - ApiKeyAuth:
        - read:volume
        - read:cloud
      - CookieAuth:
        - read:volume
        - read:cloud
      summary: Get volume
      tags:
      - volumes
      x-cli-table-default:
      - name
      - size
      - cloud
      - location
      - attached_to
      - tags
      x-cli-table-extended:
      - id
      - name
      - size
      - cloud
      - location
      - external_id
      - attached_to
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.volumes_controller
    put:
      description: Edit target volume
      operationId: edit_volume
      security:
      - ApiKeyAuth:
        - edit:volume
        - read:cloud
      - CookieAuth:
        - edit:volume
        - read:cloud
      summary: Edit volume
      tags:
      - volumes
      x-openapi-router-controller: mist_api_v2.controllers.volumes_controller
  /api/v2/zones:
    get:
      description: List zones owned by the active org. READ permission required on
        zone & cloud.
      operationId: list_zones
      security:
      - ApiKeyAuth:
        - read:zone
        - read:cloud
      - CookieAuth:
        - read:zone
        - read:cloud
      summary: List zones
      tags:
      - zones
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
    post:
      description: "Creates one or more zones on the specified cloud. If async is\
        \ true, a jobId will be returned.\nREAD permission required on cloud. CREATE_RESOURCES\
        \ permission required on cloud. CREATE permission required on zone.\n"
      operationId: create_zone
      security:
      - ApiKeyAuth:
        - create:zone
        - read:cloud
        - create_resources:cloud
      - CookieAuth:
        - create:zone
        - read:cloud
        - create_resources:cloud
      summary: Create zone
      tags:
      - zones
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
  /api/v2/zones/{zone}:
    delete:
      description: Delete target zone
      operationId: delete_zone
      security:
      - ApiKeyAuth:
        - read:zone
        - delete:zone
        - read:cloud
      - CookieAuth:
        - read:zone
        - delete:zone
        - read:cloud
      summary: Delete zone
      tags:
      - zones
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
    get:
      description: Get details about target zone
      operationId: get_zone
      security:
      - ApiKeyAuth:
        - read:zone
        - read:cloud
      - CookieAuth:
        - read:zone
        - read:cloud
      summary: Get zone
      tags:
      - zones
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - location
      - external_id
      - subnets
      - machines
      - tags
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
    put:
      description: Edit target zone
      operationId: edit_zone
      security:
      - ApiKeyAuth:
        - edit:zone
      - CookieAuth:
        - edit:zone
      summary: Edit zone
      tags:
      - zones
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
  /api/v2/zones/{zone}/records:
    get:
      description: Lists all DNS records for a particular zone. READ permission required
        on zone and record.
      operationId: list_records
      security:
      - ApiKeyAuth:
        - read:zone
        - read:record
      - CookieAuth:
        - read:zone
        - read:record
      summary: List records
      tags:
      - zones
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
    post:
      description: Creates a new record under a specific zone. CREATE_RESOURCES permission
        required on cloud. CREATE_RECORDS permission required on zone
      operationId: create_record
      security:
      - ApiKeyAuth:
        - read:zone
        - read:cloud
        - create_resources:cloud
        - create_records:zone
      - CookieAuth:
        - read:zone
        - read:cloud
        - create_resources:cloud
        - create_records:zone
      summary: Create record
      tags:
      - zones
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
  /api/v2/zones/{zone}/records/{record}:
    delete:
      description: Deletes a specific DNS record under a zone. REMOVE permission required
        on zone.
      operationId: delete_record
      security:
      - ApiKeyAuth:
        - remove:zone
      - CookieAuth:
        - remove:zone
      summary: Delete record
      tags:
      - zones
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
    get:
      description: Get details about target record
      operationId: get_record
      security:
      - ApiKeyAuth:
        - read:zone
        - read:cloud
      - CookieAuth:
        - read:zone
        - read:cloud
      summary: Get record
      tags:
      - zones
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - owned_by
      - created_by
      x-openapi-router-controller: mist_api_v2.controllers.zones_controller
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: mist_api_v2.controllers.security_controller_.info_from_ApiKeyAuth
    CookieAuth:
      in: cookie
      name: session.id
      type: apiKey
      x-apikeyInfoFunc: mist_api_v2.controllers.security_controller_.info_from_CookieAuth
x-cli-waiters:
  job-finished:
    short: Wait job
    long: Wait until job finishes
    delay: 2
    attempts: 900
    retryCodes:
    - 404
    operationId: get-job
    matchers:
    - select: response.body#data.error
      test: notEqual
      expected: false
      state: failure
    - select: response.body#data.finished_at
      test: notEqual
      expected: 0
      state: success
    updates: "response.body#data.logs[:].action"
    after:
      create-machine:
        job_id: response.body#jobId
